const fs = require('fs');
const path = require('path');

// 1. Back up original files
const filesToBackup = [
  'src/data/yuriSeries.ts',
  'src/data/yuriCharacters.ts',
  'src/data/yuriShips.ts',
  'src/data/yuriSongs.ts',
  'src/data/yuriEmojis.ts'
];

filesToBackup.forEach(f => {
  const backup = f + '.bak';
  if (!fs.existsSync(backup)) {
    fs.copyFileSync(f, backup);
    console.log(`Backed up ${f} to ${backup}`);
  }
});

// Helper to parse typescript array
function parseTs(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const start = content.indexOf('[');
  const end = content.lastIndexOf(']');
  const jsonStr = content.slice(start, end + 1);
  return eval(jsonStr);
}

// Helper to write typescript array
function writeTs(filePath, exportName, typeName, data) {
  const tsContent = `import { ${typeName} } from '../types/yuri';\n\nexport const ${exportName}: ${typeName}[] = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(filePath, tsContent, 'utf8');
  console.log(`Wrote ${data.length} items to ${filePath}`);
}

// ----------------------------------------------------
// Step 1: yuriSeries.ts
// ----------------------------------------------------
const seriesList = parseTs('src/data/yuriSeries.ts');

const new29Series = [
  {
    id: "crown-handler",
    title: "Princess Principal: Crown Handler",
    romaji: "Princess Principal: Crown Handler",
    nativeTitle: "プリンセス・プリンシパル Crown Handler",
    medium: "Anime",
    releaseYear: 2021,
    origin: "Japan",
    setting: "Historical",
    tropes: ["Royalty & Commoner", "Opposites Attract"],
    tone: "Action/Adventure",
    status: "Ongoing",
    synopsis: "In the steampunk capital of London divided by an enormous wall, five teenage spies undertake thrilling espionage missions under the undercover guise of noble high school girls.",
    famousQuote: "I am an alien from the Black Lizard Planet.",
    coverImage: "https://media.kitsu.app/anime/poster_images/41254/large.jpg",
    pairing: "Ange le Carré x Charlotte",
    aliases: ["Crown Handler", "PriPri Crown Handler", "Princess Principal Movie"]
  },
  {
    id: "kageki-shojo",
    title: "Kageki Shojo!!",
    romaji: "Kageki Shoujo!!",
    nativeTitle: "かげきしょうじょ!!",
    medium: "Anime",
    releaseYear: 2021,
    origin: "Japan",
    setting: "High School",
    tropes: ["Roommates", "Opposites Attract"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "At the Kouka Kageki Musical Drama Academy, aspiring young actresses train vigorously for theatrical stardom, forging deep, life-altering bonds on and off the stage.",
    famousQuote: "I'm going to be Oscar!",
    coverImage: "https://media.kitsu.app/anime/poster_images/44206/large.jpg",
    pairing: "Sarasa Watanabe x Ai Narata",
    aliases: ["Kageki Shoujo!!", "Opera Girl!"]
  },
  {
    id: "wataten-movie",
    title: "WATATEN!: An Angel Flew Down to Me: Precious Friends",
    romaji: "Watashi ni Tenshi ga Maiorita! Precious Friends",
    nativeTitle: "私に天使が舞いおりた！ プレシャス・フレンズ",
    medium: "Anime",
    releaseYear: 2022,
    origin: "Japan",
    setting: "High School",
    tropes: ["Senpai & Kouhai", "Opposites Attract"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "Miyako, Hana, Hinata and their friends embark on a heartwarming countryside trip in this theatrical feature film extension of the beloved comedy.",
    famousQuote: "Mya-nee is the best sister ever!",
    coverImage: "https://media.kitsu.app/anime/45323/poster_image/large-42e3bbc961f2a612b31b81453f678970.jpeg",
    pairing: "Miyako Hoshino x Hana Shirosaki",
    aliases: ["Wataten Movie", "Precious Friends"]
  },
  {
    id: "shimeji-simulation",
    title: "Shimeji Simulation",
    romaji: "Shimeji Simulation",
    nativeTitle: "シメジ シミュレーション",
    medium: "Manga",
    releaseYear: 2019,
    origin: "Japan",
    setting: "High School",
    tropes: ["Opposites Attract", "Slow Burn"],
    tone: "Dark/Psychological",
    status: "Completed",
    synopsis: "After spending two years hiding in a closet, Shijima Tsukishima returns to school only to discover mushrooms sprouting from her head, befriending a girl with a fried egg on her head.",
    famousQuote: "I just wanted to stay rolled up in a futon forever.",
    coverImage: "https://media.kitsu.app/manga/poster_images/54303/large.jpg",
    pairing: "Shijima Tsukishima x Majime Yamashita",
    aliases: ["Shimeji", "Tsukumizu Shimeji"]
  },
  {
    id: "kin-iro-movie",
    title: "Kin-iro Mosaic: Thank You!!",
    romaji: "Kin-iro Mosaic: Thank You!!",
    nativeTitle: "きんいろモザイク Thank You!!",
    medium: "Anime",
    releaseYear: 2021,
    origin: "Japan",
    setting: "High School",
    tropes: ["Childhood Friends", "Opposites Attract"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "During their high school senior year trip to Nara and Kyoto, Shinobu, Alice, Aya, Yoko, and Karen celebrate their enduring friendship before graduation.",
    famousQuote: "England and Japan might be far apart, but our hearts are always together!",
    coverImage: "https://media.kitsu.app/anime/poster_images/43107/large.jpg",
    pairing: "Shinobu Oomiya x Alice Cartelet",
    aliases: ["Kinmoza Thank You", "Kinmoza Movie"]
  },
  {
    id: "i-love-amy",
    title: "I Love Amy",
    romaji: "I Love Amy",
    nativeTitle: "아이 러브 에이미",
    medium: "Manhwa/Webtoon",
    releaseYear: 2021,
    origin: "South Korea",
    setting: "High School",
    tropes: ["Opposites Attract", "Enemies to Lovers"],
    tone: "Dark/Psychological",
    status: "Completed",
    synopsis: "Amy, a kind and innocent high school girl, finds herself the target of Bibi, a deeply traumatized and obsessive girl who resolves to conquer Amy's heart whatever it takes.",
    famousQuote: "I want to become someone you can never forget.",
    coverImage: "https://uploads.mangadex.org/covers/52ab10b8-d539-4839-9b31-7937fb08c813/47b42779-8412-423a-95fe-80da1271f2be.jpg.512.jpg",
    pairing: "Bibi x Amy",
    aliases: ["Amy", "I Love Amy Manhwa"]
  },
  {
    id: "a-joyful-life",
    title: "A Joyful Life",
    romaji: "A Joyful Life",
    nativeTitle: "즐거운 나의 집",
    medium: "Manhwa/Webtoon",
    releaseYear: 2018,
    origin: "South Korea",
    setting: "College/Adult",
    tropes: ["Slow Burn", "Opposites Attract"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "Da-kyeong carries deep past trauma and emotional scars, but her quiet life shifts when Seon-hwa re-enters her world, challenging her walls and reigniting hidden affection.",
    famousQuote: "Was my life ever truly joyful before I met you?",
    coverImage: "https://uploads.mangadex.org/covers/215e3ced-247e-4f34-8e1a-27b60ffef8ac/d75851aa-7307-485d-aafb-a434e02326fe.jpg.512.jpg",
    pairing: "Da-kyeong x Seon-hwa",
    aliases: ["Joyful Life", "Pleasant My House"]
  },
  {
    id: "lily-love-2",
    title: "Lily Love 2: Flare",
    romaji: "Lily Love 2: Flare",
    nativeTitle: "Lily Love 2: Flare",
    medium: "Manhwa/Webtoon",
    releaseYear: 2018,
    origin: "Other",
    setting: "College/Adult",
    tropes: ["Opposites Attract", "Slow Burn"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "The standalone companion to Ratana Satis' hit GL series, following Ice and Ploy as they navigate painful past heartbreaks, adult responsibilities, and an irresistible mutual flame.",
    famousQuote: "Ice, let the warmth of our love melt every regret you've ever held.",
    coverImage: "https://media.kitsu.app/manga/poster_images/57563/large.jpg",
    pairing: "Ice x Ploy",
    aliases: ["Lily Love Flare", "Lily Love 2", "Ratana Satis Flare"]
  },
  {
    id: "futarigurashi",
    title: "Futarigurashi",
    romaji: "Futarigurashi",
    nativeTitle: "ふたりぐらし",
    medium: "Manga",
    releaseYear: 2020,
    origin: "Japan",
    setting: "College/Adult",
    tropes: ["Roommates", "Opposites Attract"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "A cozy and charming slice-of-life manga capturing the quiet tenderness, domestic routines, and sweet mutual affection of two women living together in their shared apartment.",
    famousQuote: "Every small moment we share across the dinner table is precious.",
    coverImage: "https://uploads.mangadex.org/covers/4cc14713-e34c-456f-a8a1-a07084240199/ef48be68-651f-4843-9a11-c74e5df4da13.jpg.512.jpg",
    pairing: "Saeko x Miwa",
    aliases: ["Living Together", "Futari Gurashi"]
  },
  {
    id: "my-girlfriends-not-here-today",
    title: "My Girlfriend's Not Here Today",
    romaji: "Kyou wa Kanojo ga Inai kara",
    nativeTitle: "今日は彼女がいないから",
    medium: "Manga",
    releaseYear: 2021,
    origin: "Japan",
    setting: "High School",
    tropes: ["Love Triangle", "Opposites Attract"],
    tone: "Drama/Angst",
    status: "Ongoing",
    synopsis: "Feeling neglected by her busy girlfriend, Yuni allows herself to get close to Nanase, tumbling into a passionate, guilt-ridden, and toxic secret high school relationship.",
    famousQuote: "Today my girlfriend isn't here... so what are we going to do?",
    coverImage: "https://uploads.mangadex.org/covers/af5f2646-cddd-4c4c-b652-96577ed89647/3848315f-7230-46dc-8b95-00625d9d7f27.jpg.512.jpg",
    pairing: "Yuni Jinbo x Nanase Maekawa",
    aliases: ["Kyou wa Kanojo ga Inai kara", "No Girlfriend Today"]
  },
  {
    id: "show-me-your-bust",
    title: "Show Me Your Bust",
    romaji: "Show Me Your Bust",
    nativeTitle: "가슴을 보여줘",
    medium: "Manhwa/Webtoon",
    releaseYear: 2021,
    origin: "South Korea",
    setting: "College/Adult",
    tropes: ["Opposites Attract", "Enemies to Lovers"],
    tone: "Comedy",
    status: "Completed",
    synopsis: "An energetic workplace comedy about lingerie designers Jiho and Woori, whose initial fiery rivalry quickly blossoms into unexpected romantic desire.",
    famousQuote: "Design is all about finding the perfect match—and so are we.",
    coverImage: "https://uploads.mangadex.org/covers/73965527-b393-4f65-9bc3-2439ec44935a/2eb7463e-40e3-4306-ba38-6df573d5e68d.png.512.jpg",
    pairing: "Jiho x Woori",
    aliases: ["Show Me Your Bust Manhwa", "Bust Webtoon"]
  },
  {
    id: "hello-melancholic",
    title: "Hello, Melancholic!",
    romaji: "Hello, Melancholic!",
    nativeTitle: "ハロー・メランコリック！",
    medium: "Manga",
    releaseYear: 2019,
    origin: "Japan",
    setting: "High School",
    tropes: ["Senpai & Kouhai", "Opposites Attract"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "Tall, self-conscious trombone player Asuka Minato wants nothing more than to blend into the background, until bubbly flutist Saki Tone insists they play concert music together.",
    famousQuote: "Your sound isn't clumsy at all; it's the warmest thing I've ever heard.",
    coverImage: "https://uploads.mangadex.org/covers/153fa167-9a08-4e67-a82d-c36affddd36c/b8a34ec8-132a-4ab9-8641-e8604b2f56e1.jpg.512.jpg",
    pairing: "Asuka Minato x Saki Tone",
    aliases: ["Hello Melancholic", "Yayoi Osawa"]
  },
  {
    id: "assault-lily-league",
    title: "Assault Lily: League of Gardens - Full Bloom",
    romaji: "Assault Lily: League of Gardens - Full Bloom",
    nativeTitle: "アサルトリリィ League of Gardens -フルブルーム-",
    medium: "Manga",
    releaseYear: 2020,
    origin: "Japan",
    setting: "Fantasy/Magic",
    tropes: ["Senpai & Kouhai", "Roommates"],
    tone: "Action/Adventure",
    status: "Completed",
    synopsis: "At Yurigaoka Girls' Academy, Lilies wield CHARM weaponry to defend humanity against the enigmatic Huge, fighting side by side with unbreakable sisterly camaraderie.",
    famousQuote: "As long as I fight beside you, my blade will never hesitate.",
    coverImage: "https://uploads.mangadex.org/covers/f239fcd4-9f7f-4296-9e52-ee5a66a7e938/423f1581-b27b-4e89-8b88-deeb330f5c08.jpg.512.jpg",
    pairing: "Riri Hitotsuyanagi x Yuyu Shirai",
    aliases: ["Assault Lily Manga", "League of Gardens Full Bloom"]
  },
  {
    id: "sheep-princess",
    title: "The Sheep Princess in Wolf's Clothing",
    romaji: "Ookami no Kawa wo Kabutta Hitsujihime",
    nativeTitle: "狼の皮をかぶった羊姫",
    medium: "Manga",
    releaseYear: 2020,
    origin: "Japan",
    setting: "Fantasy/Magic",
    tropes: ["Master & Servant", "Royalty & Commoner"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "In a world divided between sheep and wolves, the timid sheep princess Momo is assigned the fiercely loyal wolf bodyguard Aki, leading to an adorable fairytale romance.",
    famousQuote: "You don't have to be afraid of my claws, Princess. They exist only to protect you.",
    coverImage: "https://uploads.mangadex.org/covers/7dc8bfc9-876b-4c34-b6e7-4560438095bf/072ed91b-88b1-4e9f-ba1d-936cf21f3265.png.512.jpg",
    pairing: "Momo x Aki",
    aliases: ["Ookami no Kawa wo Kabutta Hitsujihime", "Wolf's Clothing Sheep Princess"]
  },
  {
    id: "superwomen-in-love",
    title: "Superwomen in Love! Honey Trap and Rapid Rabbit",
    romaji: "Hero-san to Moto Onna Kanbu-san",
    nativeTitle: "ヒーローさんと元女幹部さん",
    medium: "Manga",
    releaseYear: 2020,
    origin: "Japan",
    setting: "Supernatural",
    tropes: ["Enemies to Lovers", "Opposites Attract"],
    tone: "Action/Adventure",
    status: "Completed",
    synopsis: "Honey Trap, a gorgeous high-ranking commander of an evil syndicate, defects from her organization after falling head-over-heels in love with superheroine Rapid Rabbit.",
    famousQuote: "I conquered the villains only to let you conquer my heart!",
    coverImage: "https://uploads.mangadex.org/covers/724dd143-c35c-478a-9cd8-fa8b58eca714/275be978-020f-49bc-8e00-2e831d3a9d3a.jpg.512.jpg",
    pairing: "Honey Trap x Rapid Rabbit",
    aliases: ["Hero-san to Moto Onna Kanbu-san", "Honey Trap Rapid Rabbit"]
  },
  {
    id: "catulus-syndrome",
    title: "Catulus Syndrome",
    romaji: "Nekogurashi no Catulus Syndrome",
    nativeTitle: "ねこ暮らしのカトゥールス・シンドローム",
    medium: "Manga",
    releaseYear: 2017,
    origin: "Japan",
    setting: "High School",
    tropes: ["Opposites Attract", "Childhood Friends"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "Yuki suffers from Catulus Syndrome, causing her to turn into an adorable feline when excited. Her life brightens when sweet classmate Riko takes her under her wing.",
    famousQuote: "Whenever I'm with you, my tail won't stop wagging!",
    coverImage: "https://media.kitsu.app/manga/poster_images/58651/large.jpg",
    pairing: "Yuki x Riko",
    aliases: ["Catulus Syndrome", "Nekogurashi"]
  },
  {
    id: "dear-my-teacher",
    title: "Dear My Teacher",
    romaji: "Dear My Teacher",
    nativeTitle: "친애하는 나의 선생님",
    medium: "Manhwa/Webtoon",
    releaseYear: 2021,
    origin: "South Korea",
    setting: "High School",
    tropes: ["Age Gap", "Senpai & Kouhai"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "A high school student forms an intense, emotionally entangled connection with her literature teacher, exploring boundaries, unspoken longing, and mutual solace.",
    famousQuote: "The only lesson I could never learn was how to stop loving you.",
    coverImage: "https://media.kitsu.app/manga/poster_images/40185/large.jpg",
    pairing: "Ye-seul x Eun-chae",
    aliases: ["Dear My Teacher Manhwa"]
  },
  {
    id: "green-tea-bitch",
    title: "Green Tea Bitch",
    romaji: "Lvcha Bia Xinji Gonglve",
    nativeTitle: "绿茶婊心机攻略",
    medium: "Manhua",
    releaseYear: 2020,
    origin: "China",
    setting: "High School",
    tropes: ["Enemies to Lovers", "Fake Dating"],
    tone: "Comedy",
    status: "Completed",
    synopsis: "Calculating campus queen Lin Luo attempts to expose the seemingly innocent Zhang Xinyue, only to discover Xinyue's scheming persona is equally matched—and deeply captivating.",
    famousQuote: "You think you're the only one who knows how to play this game?",
    coverImage: "https://uploads.mangadex.org/covers/69cac3f9-23cf-4a64-b83b-ad22f9e09669/1d376704-8919-4541-a4d9-880c1f499da2.jpg.512.jpg",
    pairing: "Lin Luo x Zhang Xinyue",
    aliases: ["Green Tea Bitch Manhua", "Green Tea"]
  },
  {
    id: "kitanai-kimi",
    title: "I Love Your Cruddy...",
    romaji: "Kitanai Kimi ga Ichiban Kawaii",
    nativeTitle: "きたない君がいちばんかわいい",
    medium: "Manga",
    releaseYear: 2019,
    origin: "Japan",
    setting: "High School",
    tropes: ["Opposites Attract", "Slow Burn"],
    tone: "Dark/Psychological",
    status: "Completed",
    synopsis: "Two troubled high school girls engage in an escalating, twisted fetishistic secret relationship behind closed classroom doors, bound by desperation and distorted love.",
    famousQuote: "You're at your absolute cutest when you're completely broken down.",
    coverImage: "https://media.kitsu.app/manga/poster_images/49472/large.jpg",
    pairing: "Saya x Hinako",
    aliases: ["Kitanai Kimi", "KitaKawa", "I Love Your Cruddy"]
  },
  {
    id: "futari-monologue",
    title: "The Two of Them Are Pretty Much Like This",
    romaji: "Futari Monologue",
    nativeTitle: "ふたりモノローグ",
    medium: "Manga",
    releaseYear: 2017,
    origin: "Japan",
    setting: "High School",
    tropes: ["Childhood Friends", "Opposites Attract"],
    tone: "Comedy",
    status: "Completed",
    synopsis: "Timid Hinata and delinquent-looking Mikage used to be best friends in elementary school. Reunited in high school, their internal monologues clash in hilarious misunderstandings.",
    famousQuote: "She looks so intimidating, but I still want to be close to her!",
    coverImage: "https://uploads.mangadex.org/covers/1de44b9c-29b2-4c21-b4f7-baaa36cebef9/255656d0-ca06-407c-aa1d-ffc713a49fb5.jpg.512.jpg",
    pairing: "Hinata x Mikage",
    aliases: ["Futari Monologue", "Two Monologues"]
  },
  {
    id: "ride-or-die",
    title: "Ride or Die",
    romaji: "Kanojo (Ride or Die)",
    nativeTitle: "彼女",
    medium: "Anime",
    releaseYear: 2021,
    origin: "Japan",
    setting: "College/Adult",
    tropes: ["Enemies to Lovers", "Slow Burn"],
    tone: "Dark/Psychological",
    status: "Completed",
    synopsis: "Rei murders her former classmate Nanae's abusive husband out of fierce, lingering devotion, prompting the two women to flee across Japan on a reckless, poignant road trip.",
    famousQuote: "I killed him for you. Where do we go now?",
    coverImage: "https://uploads.mangadex.org/covers/d964361f-042a-4c1b-907d-3c907dd50060/ccf6797d-71b6-4236-ac63-2b0fd1b635b1.jpg.512.jpg",
    pairing: "Rei Nagasawa x Nanae Shinoda",
    aliases: ["Ride or Die", "Ching Nakamura Kanojo"]
  },
  {
    id: "my-cute-little-kitten",
    title: "My Cute Little Kitten",
    romaji: "Gwichanheun Goyang-i",
    nativeTitle: "귀찮은 고양이",
    medium: "Manhwa/Webtoon",
    releaseYear: 2019,
    origin: "South Korea",
    setting: "College/Adult",
    tropes: ["Roommates", "Opposites Attract"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "A warm, heartwarming Korean GL webtoon following the daily domestic cohabitation and budding romance between a weary office worker and an enigmatic young woman.",
    famousQuote: "Living with you made my quiet apartment feel like home.",
    coverImage: "https://uploads.mangadex.org/covers/2e71d530-79b7-444d-89c9-29f9534d08d2/9ef31169-1627-43db-ac34-d266b938d687.jpg.512.jpg",
    pairing: "So-eun x Da-jeong",
    aliases: ["Cute Kitten Manhwa", "My Cute Little Kitten"]
  },
  {
    id: "tsubame-tip-off",
    title: "Tsubame Tip-Off!",
    romaji: "Tsubame Tip-Off!",
    nativeTitle: "つばめティップオフ！",
    medium: "Manga",
    releaseYear: 2020,
    origin: "Japan",
    setting: "High School",
    tropes: ["Opposites Attract", "Senpai & Kouhai"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "Tall, shy high schooler Tsubame joins the girls' basketball team, discovering newfound athletic confidence and heartfelt team chemistry alongside her inspiring teammates.",
    famousQuote: "On this court, every pass we make brings us closer.",
    coverImage: "https://uploads.mangadex.org/covers/71937147-e3e7-4ba6-9cd9-912b8289223d/8bc43fd7-0e84-4900-8fd2-fe6b0354726b.jpg.512.jpg",
    pairing: "Tsubame Okeda x Ibuki Minato",
    aliases: ["Tsubame Tip-Off", "Tsubame Basketball"]
  },
  {
    id: "kanojo-to-himitsu",
    title: "Kanojo to Himitsu to Koimoyou",
    romaji: "Kanojo to Himitsu to Koimoyou",
    nativeTitle: "彼女とヒミツと恋もよう",
    medium: "Manga",
    releaseYear: 2017,
    origin: "Japan",
    setting: "High School",
    tropes: ["Opposites Attract", "Slow Burn"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "A tender high school romance chronicling two girls who discover each other's hidden secrets, finding solace, encouragement, and genuine first love together.",
    famousQuote: "Sharing secrets with you became my favorite time of the day.",
    coverImage: "https://uploads.mangadex.org/covers/831b12b8-2d0e-4397-8719-1efee4c32f40/0f411c81-14a6-4d59-9e57-869d839c4972.jpg.512.jpg",
    pairing: "Karin x Shiori",
    aliases: ["Her and Secrets and Patterns of Love", "Kanojo to Himitsu"]
  },
  {
    id: "vanadis-heart",
    title: "Mobile Suit Gundam: The Witch from Mercury - Vanadis Heart",
    romaji: "Kidou Senshi Gundam: Suisei no Majo - Vanadis Heart",
    nativeTitle: "機動戦士ガンダム 水星の魔女 ヴァナディースハート",
    medium: "Manga",
    releaseYear: 2023,
    origin: "Japan",
    setting: "Sci-Fi/Mecha",
    tropes: ["Opposites Attract", "Master & Servant"],
    tone: "Action/Adventure",
    status: "Completed",
    synopsis: "Set five years after the Vanadis Incident, Kiyashu travels the Earth Sphere piloting the Gundam Lfrith Jiu, crossing paths with Vayuela in an expanding mecha saga.",
    famousQuote: "The curse of the GUND format will not stop us from forging our own path.",
    coverImage: "https://uploads.mangadex.org/covers/ddd44276-89d1-4b8c-89e6-f5ea24e44079/aca50bd4-5e25-4dd8-8291-7ca52ba58bb9.jpg.512.jpg",
    pairing: "Kiyashu x Vayuela",
    aliases: ["Vanadis Heart", "G-Witch Vanadis"]
  },
  {
    id: "lycoris-recollect",
    title: "Lycoris Recoil: Recollect",
    romaji: "Lycoris Recoil: Recollect",
    nativeTitle: "リコリス・リコイル リコレクト",
    medium: "Manga",
    releaseYear: 2022,
    origin: "Japan",
    setting: "Workplace",
    tropes: ["Opposites Attract", "Roommates"],
    tone: "Comedy",
    status: "Completed",
    synopsis: "The official lighthearted comedy spinoff manga showcasing the hilarious and endearing daily café hijinks of Chisato Nishikigi and Takina Inoue at Café LycoReco.",
    famousQuote: "Another peaceful day at Café LycoReco with you!",
    coverImage: "https://uploads.mangadex.org/covers/0d6867bd-b15c-470f-a40b-b77256b3c866/8415be51-dfca-45c0-a32b-b47027fac4e7.jpg.512.jpg",
    pairing: "Chisato Nishikigi x Takina Inoue",
    aliases: ["LycoReco Recollect", "Lycoris Recollect"]
  },
  {
    id: "saeki-sayaka",
    title: "Bloom Into You: Regarding Saeki Sayaka",
    romaji: "Yagate Kimi ni Naru: Saeki Sayaka ni Tsuite",
    nativeTitle: "やがて君になる 佐伯沙弥香について",
    medium: "Light Novel",
    releaseYear: 2018,
    origin: "Japan",
    setting: "College/Adult",
    tropes: ["Slow Burn", "Senpai & Kouhai"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "Hitoma Iruma's celebrated spin-off light novel trilogy tracing Sayaka Saeki's personal journey from middle school to university as she ultimately discovers lasting love with Haru.",
    famousQuote: "I never gave up on loving girls, and because of that, I finally found you.",
    coverImage: "https://media.kitsu.app/manga/poster_images/58642/large.jpg",
    pairing: "Sayaka Saeki x Haru Edamoto",
    aliases: ["Regarding Saeki Sayaka", "Sayaka Spinoff", "Saeki Sayaka LN"]
  },
  {
    id: "everyday-lily",
    title: "Everyday Lily",
    romaji: "Everyday Lily",
    nativeTitle: "에브리데이 릴리",
    medium: "Manhwa/Webtoon",
    releaseYear: 2018,
    origin: "South Korea",
    setting: "College/Adult",
    tropes: ["Roommates", "Opposites Attract"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "A witty, delightful college romance tracking roommates Hanna and Nayoung through relatable campus shenanigans, banter, and their gradually evolving romantic chemistry.",
    famousQuote: "Sharing a dorm with you is complete chaos, but I wouldn't trade it for the world.",
    coverImage: "https://uploads.mangadex.org/covers/42224017-e415-484f-9cbd-df119472839d/c111eb68-7631-4e6d-8409-eef208fb1424.jpg.512.jpg",
    pairing: "Hanna x Nayoung",
    aliases: ["Everyday Lily Manhwa", "Everyday Lily"]
  },
  {
    id: "serenade",
    title: "Serenade",
    romaji: "Serenade",
    nativeTitle: "세레나데",
    medium: "Manhwa/Webtoon",
    releaseYear: 2018,
    origin: "South Korea",
    setting: "College/Adult",
    tropes: ["Opposites Attract", "Slow Burn"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "A poignant college music department drama centering around classical piano students Yoo-jin and Hye-ji as competition, artistic passion, and profound emotional attachment intertwine.",
    famousQuote: "Every chord I play on this piano is an unspoken confession to you.",
    coverImage: "https://media.kitsu.app/anime/poster_images/13261/large.jpg",
    pairing: "Yoo-jin x Hye-ji",
    aliases: ["Serenade Manhwa", "Serenade GL"]
  }
];

// Mapping of 29 pre-2010 IDs to replace
const replaceMap = {
  'dirty-pair': new29Series[0],
  'top-wo-nerae-gunbuster': new29Series[1],
  'dear-brother': new29Series[2],
  'revolutionary-girl-utena': new29Series[3],
  'utena': new29Series[4],
  'noir': new29Series[5],
  'princess-tutu': new29Series[6],
  'haibane-renmei': new29Series[7],
  'kiddy-grade': new29Series[8],
  'strawberry-panic': new29Series[9],
  'aoi-hana': new29Series[10],
  'maria-watches-over-us': new29Series[11],
  'maria-sama': new29Series[12],
  'kannazuki-no-miko': new29Series[13],
  'mai-hime': new29Series[14],
  'madlax': new29Series[15],
  'ichigo-mashimaro': new29Series[16],
  'girl-friends': new29Series[17],
  'simoun': new29Series[18],
  'kashimashi': new29Series[19],
  'gunjou': new29Series[20],
  'blue-drop': new29Series[21],
  'el-cazador': new29Series[22],
  'poor-poor-lips': new29Series[23],
  'candy-boy': new29Series[24],
  'octave': new29Series[25],
  'mnemosyne': new29Series[26],
  'kanamemo': new29Series[27],
  'sasameki-koto': new29Series[28]
};

// 7 series modernizations
const modernizedSeriesUpdates = {
  'yuruyuri': { releaseYear: 2011 },
  'k-on': { releaseYear: 2010 },
  'qualia-the-purple': { releaseYear: 2011 },
  'saki': { releaseYear: 2012 },
  'strike-witches': { releaseYear: 2010 },
  'maria-holic': { releaseYear: 2011 },
  'sailor-moon-s': {
    title: "Sailor Moon Crystal: Season III",
    romaji: "Bishoujo Senshi Sailor Moon Crystal Season III",
    nativeTitle: "美少女戦士セーラームーンCrystal 第3期",
    releaseYear: 2016,
    coverImage: "https://media.kitsu.app/anime/poster_images/11415/large.jpg",
    synopsis: "The definitive modern anime adaptation of the Infinity Arc. Sailor Uranus (Haruka Tenoh) and Sailor Neptune (Michiru Kaioh) fight alongside the Sailor Guardians against the Death Busters.",
    famousQuote: "A new era is calling for us.",
    aliases: ["Sailor Moon Crystal Season 3", "Crystal Season III", "Death Busters", "Haruka Michiru"]
  }
};

const updatedSeriesList = seriesList.map(s => {
  if (replaceMap[s.id]) {
    return replaceMap[s.id];
  }
  if (modernizedSeriesUpdates[s.id]) {
    return { ...s, ...modernizedSeriesUpdates[s.id] };
  }
  return s;
});

writeTs('src/data/yuriSeries.ts', 'YURI_SERIES', 'YuriSeries', updatedSeriesList);

console.log("Updated yuriSeries.ts successfully!");
