const fs = require('fs');
const path = require('path');

// 1. Expand yuriSeries.ts
const newSeries = [
  {
    id: "utena",
    title: "Revolutionary Girl Utena",
    romaji: "Shoujo Kakumei Utena",
    nativeTitle: "少女革命ウテナ",
    medium: "Anime",
    releaseYear: 1997,
    origin: "Japan",
    setting: "Fantasy/Magic",
    tropes: ["Royalty & Commoner", "Opposites Attract", "Enemies to Lovers"],
    tone: "Dark/Psychological",
    status: "Completed",
    synopsis: "Utena Tenjou strives to become a noble prince after receiving a rose-crested ring. At Ohtori Academy, she wins the Rose Bride Anthy Himemiya in a surreal sword duel, triggering a battle to revolutionize the world.",
    famousQuote: "If it cannot break out of its shell, the chick will die without being born. We are the chick; the world is our egg!",
    coverImage: "https://media.kitsu.app/anime/poster_images/251/large.jpg",
    pairing: "Utena Tenjou x Anthy Himemiya",
    aliases: ["Utena", "Shoujo Kakumei Utena", "Rose Bride", "Ikuhara"]
  },
  {
    id: "sailor-moon-s",
    title: "Sailor Moon S",
    romaji: "Bishoujo Senshi Sailor Moon S",
    nativeTitle: "美少女戦士セーラームーンS",
    medium: "Anime",
    releaseYear: 1994,
    origin: "Japan",
    setting: "Supernatural",
    tropes: ["Opposites Attract", "Master & Servant", "Slow Burn"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "The third season of Sailor Moon introduces the outer Sailor Guardians: the cool race-car driver Haruka Tenoh (Sailor Uranus) and graceful violinist Michiru Kaioh (Sailor Neptune), sharing anime's most legendary romantic lesbian bond.",
    famousQuote: "A world without Michiru isn't a world worth saving!",
    coverImage: "https://media.kitsu.app/anime/poster_images/855/large.jpg",
    pairing: "Haruka Tenoh x Michiru Kaioh",
    aliases: ["Sailor Uranus", "Sailor Neptune", "HaruMichi", "Sailor Moon"]
  },
  {
    id: "kannazuki-no-miko",
    title: "Destiny of the Shrine Maiden",
    romaji: "Kannazuki no Miko",
    nativeTitle: "神無月の巫女",
    medium: "Anime",
    releaseYear: 2004,
    origin: "Japan",
    setting: "Sci-Fi/Mecha",
    tropes: ["Opposites Attract", "Enemies to Lovers", "Master & Servant"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "Shy Himeko and wealthy, adored Chikane are reincarnations of the Solar and Lunar Shrine Maidens. Chikane's desperate, all-consuming devotion to protect Himeko from Orochi mecha and cosmic curses remains legendary.",
    famousQuote: "Himeko, I will become your villain, your sin, and your shield across all eternity.",
    coverImage: "https://media.kitsu.app/anime/poster_images/408/large.jpg",
    pairing: "Chikane Himemiya x Himeko Kurusugawa",
    aliases: ["Kannazuki", "Chikane", "Himeko", "Shrine Maiden"]
  },
  {
    id: "maria-sama",
    title: "Maria Watches Over Us",
    romaji: "Maria-sama ga Miteru",
    nativeTitle: "マリア様がみてる",
    medium: "Anime",
    releaseYear: 2004,
    origin: "Japan",
    setting: "High School",
    tropes: ["Senpai & Kouhai", "Opposites Attract", "Master & Servant"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "At the prestigious Catholic Lillian Girls' Academy, student council affairs run through the Soeur (sister) system, pairing elegant older students with younger disciples. Yumi Fukuzawa is swept into high society when Sachiko Ogasawara chooses her.",
    famousQuote: "Gokigenyou, Onee-sama.",
    coverImage: "https://media.kitsu.app/anime/poster_images/232/large.jpg",
    pairing: "Sachiko Ogasawara x Yumi Fukuzawa",
    aliases: ["Marimite", "Maria-sama", "Sachiko", "Yumi"]
  },
  {
    id: "simoun",
    title: "Simoun",
    romaji: "Simoun",
    nativeTitle: "シムーン",
    medium: "Anime",
    releaseYear: 2006,
    origin: "Japan",
    setting: "Sci-Fi/Mecha",
    tropes: ["Opposites Attract", "Slow Burn", "Master & Servant"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "In a world where all humans are born female and choose their permanent gender at seventeen, priestesses known as Sibyllae pilot sacred twin-seated flying vessels called Simoun to defend their realm and perform holy flight prayers.",
    famousQuote: "Our flight together is our prayer, our rebellion, and our love.",
    coverImage: "https://media.kitsu.app/anime/poster_images/1498/large.jpg",
    pairing: "Aer x Neviril",
    aliases: ["Simoun", "Sibyllae", "Aer", "Neviril"]
  },
  {
    id: "mygo",
    title: "BanG Dream! It's MyGO!!!!!",
    romaji: "BanG Dream! It's MyGO!!!!!",
    nativeTitle: "バンドリ！It's MyGO!!!!!",
    medium: "Anime",
    releaseYear: 2023,
    origin: "Japan",
    setting: "High School",
    tropes: ["Idol/Music", "Enemies to Lovers", "Opposites Attract"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "After the traumatic collapse of student band CRYCHIC, Tomori Takamatsu struggles with self-loathing until Anon, Soyo, Taki, and Rana form MyGO!!!!!, navigating unrequited emotional dependency and dramatic band confrontations.",
    famousQuote: "Why did you play Haruhikage?!",
    coverImage: "https://media.kitsu.app/anime/poster_images/47413/large.jpg",
    pairing: "Tomori Takamatsu x Anon Chihaya / Soyo Nagasaki x Sakiko Togawa",
    aliases: ["MyGO", "It's MyGO", "BanG Dream", "Haruhikage", "AnonTomo", "SoyoSaki"]
  },
  {
    id: "love-live",
    title: "Love Live! School Idol Project",
    romaji: "Love Live! School Idol Project",
    nativeTitle: "ラブライブ！",
    medium: "Anime",
    releaseYear: 2013,
    origin: "Japan",
    setting: "High School",
    tropes: ["Idol/Music", "Childhood Friends", "Opposites Attract"],
    tone: "Comedy",
    status: "Completed",
    synopsis: "Nine high school girls form the school idol group μ's to save Otonokizaka Academy from closure, creating iconic close bonds like Eli and Nozomi, Maki and Nico, and Kotori and Umi.",
    famousQuote: "If we don't do something, our school will be gone! Let's become idols!",
    coverImage: "https://media.kitsu.app/anime/poster_images/7373/large.jpg",
    pairing: "Eli Ayase x Nozomi Tojo / Nico Yazawa x Maki Nishikino",
    aliases: ["Love Live", "Muse", "NozoEli", "NicoMaki", "School Idol Project"]
  },
  {
    id: "love-live-sunshine",
    title: "Love Live! Sunshine!!",
    romaji: "Love Live! Sunshine!!",
    nativeTitle: "ラブライブ！サンシャイン!!",
    medium: "Anime",
    releaseYear: 2016,
    origin: "Japan",
    setting: "High School",
    tropes: ["Idol/Music", "Childhood Friends", "Opposites Attract"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "In the seaside town of Uchiura, Chika Takami gathers nine girls to form Aqours, following the footprints of μ's while deepening bonds between piano composer Riko, childhood friend You, and the senior trio Kanan, Mari, and Dia.",
    famousQuote: "Can nine ordinary girls shine brightly together like the dazzling sun?",
    coverImage: "https://media.kitsu.app/anime/poster_images/11833/large.jpg",
    pairing: "Chika Takami x Riko Sakurauchi / Kanan Matsuura x Mari Ohara",
    aliases: ["Aqours", "Sunshine", "ChikaRiko", "KanaMari", "Love Live Sunshine"]
  },
  {
    id: "love-live-nijigasaki",
    title: "Love Live! Nijigasaki High School Idol Club",
    romaji: "Love Live! Nijigasaki Gakuen School Idol Doukoukai",
    nativeTitle: "ラブライブ！虹ヶ咲学園スクールアイドル同好会",
    medium: "Anime",
    releaseYear: 2020,
    origin: "Japan",
    setting: "High School",
    tropes: ["Idol/Music", "Childhood Friends", "Slow Burn"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "Yu Takasaki supports her childhood friend Ayumu Uehara and the solo school idols of Nijigasaki Academy, sparking memorable romantic jealousy and devotion.",
    famousQuote: "You belong to me, don't you Yuu-chan?! Don't look at anyone else!",
    coverImage: "https://media.kitsu.app/anime/poster_images/42880/large.jpg",
    pairing: "Yu Takasaki x Ayumu Uehara",
    aliases: ["Nijigasaki", "Anigasaki", "AyuYuu", "Yu Takasaki", "Ayumu Uehara"]
  },
  {
    id: "gushing-over-magical-girls",
    title: "Gushing over Magical Girls",
    romaji: "Mahou Shoujo ni Akogarete",
    nativeTitle: "魔法少女にあこがれて",
    medium: "Anime",
    releaseYear: 2024,
    origin: "Japan",
    setting: "Fantasy/Magic",
    tropes: ["Enemies to Lovers", "Master & Servant", "Opposites Attract"],
    tone: "Comedy",
    status: "Ongoing",
    synopsis: "Hiiragi Utena adores magical girls, but after being coerced into evil organization Enormeita as Magia Baiser, she discovers an awakening sadomasochistic delight in fighting her beloved heroines.",
    famousQuote: "I really, truly love magical girls from the bottom of my wicked heart!",
    coverImage: "https://media.kitsu.app/anime/poster_images/47372/large.jpg",
    pairing: "Utena Hiiragi x Kiwi Araga",
    aliases: ["MahoAko", "Mahou Shoujo ni Akogarete", "Magia Baiser", "Leopard"]
  },
  {
    id: "watanare",
    title: "There's No Freaking Way I'll Be Your Lover! Unless...",
    romaji: "Watashi ga Koibito ni Nareru Wake Nai jan, Muri Muri!",
    nativeTitle: "わたしが恋人になれるわけないじゃん、ムリムリ！",
    medium: "Light Novel",
    releaseYear: 2020,
    origin: "Japan",
    setting: "High School",
    tropes: ["Fake Dating", "Enemies to Lovers", "Opposites Attract"],
    tone: "Comedy",
    status: "Ongoing",
    synopsis: "Socially exhausted Renako wants a normal high school friend life, but school superstar Mai Oduka confesses her love on day one! They agree to a game: are they better off as best friends or passionate lovers?",
    famousQuote: "There's no way in hell two girls can be lovers! ...Unless?!",
    coverImage: "https://media.kitsu.app/manga/poster_images/57530/large.jpg",
    pairing: "Renako Amaori x Mai Oduka",
    aliases: ["Watanare", "Renako", "Mai", "Muri Muri"]
  },
  {
    id: "the-summer-you-were-there",
    title: "The Summer You Were There",
    romaji: "Kimi to Tsuzuru Utakata",
    nativeTitle: "君と綴るうたかた",
    medium: "Manga",
    releaseYear: 2020,
    origin: "Japan",
    setting: "High School",
    tropes: ["Slow Burn", "Opposites Attract", "Fake Dating"],
    tone: "Drama/Angst",
    status: "Completed",
    synopsis: "Quiet writer Shizuku throws away her rejected manuscript, but cheerful classmate Kaori discovers it and proposes they date during summer vacation so Shizuku can write her next romance story.",
    famousQuote: "Let me be the heroine of your love story this summer.",
    coverImage: "https://media.kitsu.app/manga/poster_images/59489/large.jpg",
    pairing: "Shizuku Hoshikawa x Kaori Asaka",
    aliases: ["Kimi to Tsuzuru Utakata", "Kimitsuzu", "Kaori", "Shizuku"]
  },
  {
    id: "anemone-is-in-heat",
    title: "Anemone Is in Heat",
    romaji: "Anemone wa Netsu wo Obiru",
    nativeTitle: "アネモネは熱を帯びる",
    medium: "Manga",
    releaseYear: 2020,
    origin: "Japan",
    setting: "High School",
    tropes: ["Enemies to Lovers", "Slow Burn", "Opposites Attract"],
    tone: "Sweet/Fluff",
    status: "Ongoing",
    synopsis: "Mashiro fails her entrance exam to a top high school because she helped a sick girl on exam morning. When she enters a local school and runs into that exact girl, Nagisa, guilt and resentment blossom into tender intimacy.",
    famousQuote: "I thought I hated you for changing my destiny... but now I only want to stay with you.",
    coverImage: "https://media.kitsu.app/manga/poster_images/60458/large.jpg",
    pairing: "Mashiro Ooki x Nagisa Uda",
    aliases: ["Anemone", "Anemone wa Netsu wo Obiru", "Mashiro", "Nagisa"]
  },
  {
    id: "new-game",
    title: "New Game!",
    romaji: "NEW GAME!",
    nativeTitle: "NEW GAME!",
    medium: "Anime",
    releaseYear: 2016,
    origin: "Japan",
    setting: "Workplace",
    tropes: ["Roommates", "Master & Servant", "Opposites Attract"],
    tone: "Comedy",
    status: "Completed",
    synopsis: "Fresh high school graduate Aoba Suzukaze joins game developer Eagle Jump, working under art director Kou Yagami and supervisor Rin Toyama, whose decade-long romantic bond anchors the company.",
    famousQuote: "I'll do my best to create games that make people smile!",
    coverImage: "https://media.kitsu.app/anime/poster_images/11494/large.jpg",
    pairing: "Kou Yagami x Rin Toyama",
    aliases: ["New Game", "Eagle Jump", "KouRin", "Aoba"]
  },
  {
    id: "wataten",
    title: "WATATEN!: an Angel Flew Down to Me",
    romaji: "Watashi ni Tenshi ga Maiorita!",
    nativeTitle: "私に天使が舞い降りた！",
    medium: "Anime",
    releaseYear: 2019,
    origin: "Japan",
    setting: "High School",
    tropes: ["Childhood Friends", "Opposites Attract"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "Shy university student Miyako bakes sweets for her energetic younger sister Hinata and her best friend Noa Shirosaki, delivering heartwarming fluff and playful girl romance.",
    famousQuote: "Mya-nee! Look at how cute Noa-chan is today!",
    coverImage: "https://media.kitsu.app/anime/poster_images/41235/large.jpg",
    pairing: "Hinata Hoshino x Noa Shirosaki",
    aliases: ["Wataten", "Mya-nee", "Watashi ni Tenshi ga Maiorita"]
  },
  {
    id: "birdie-wing",
    title: "Birdie Wing: Golf Girls' Story",
    romaji: "BIRDIE WING -Golf Girls' Story-",
    nativeTitle: "BIRDIE WING -Golf Girls' Story-",
    medium: "Anime",
    releaseYear: 2022,
    origin: "Japan",
    setting: "High School",
    tropes: ["Enemies to Lovers", "Opposites Attract", "Rivals"],
    tone: "Action/Adventure",
    status: "Completed",
    synopsis: "Underground underworld golfer Eve meets high-society Japanese golf prodigy Aoi Amawashi. Bound by destiny and a promise to meet on the green, their intense romantic rivalry flips the sporting world upside down.",
    famousQuote: "Rainbow bullet! Aoi, I'm playing this golf shot solely for you!",
    coverImage: "https://media.kitsu.app/anime/poster_images/44919/large.jpg",
    pairing: "Eve x Aoi Amawashi",
    aliases: ["Birdie Wing", "EveAoi", "Rainbow Bullet", "Aoi Amawashi"]
  },
  {
    id: "akebis-sailor-uniform",
    title: "Akebi's Sailor Uniform",
    romaji: "Akebi-chan no Sailor-fuku",
    nativeTitle: "明日ちゃんのセーラー服",
    medium: "Anime",
    releaseYear: 2022,
    origin: "Japan",
    setting: "High School",
    tropes: ["Opposites Attract", "Sweet/Fluff", "Childhood Friends"],
    tone: "Sweet/Fluff",
    status: "Ongoing",
    synopsis: "Komichi Akebi has always dreamed of wearing a navy sailor uniform. Admitted into Roubai Academy, her radiant energy touches and inspires the girls around her, especially Tokyo transfer student Erika Kizaki.",
    famousQuote: "I want to make so many friends, and share all my happy days with Erika!",
    coverImage: "https://media.kitsu.app/anime/poster_images/44421/large.jpg",
    pairing: "Komichi Akebi x Erika Kizaki",
    aliases: ["Akebi", "Akebi-chan", "Erika Kizaki", "Roubai"]
  },
  {
    id: "assault-lily",
    title: "Assault Lily: Bouquet",
    romaji: "Assault Lily: Bouquet",
    nativeTitle: "アサルトリリィ BOUQUET",
    medium: "Anime",
    releaseYear: 2020,
    origin: "Japan",
    setting: "Fantasy/Magic",
    tropes: ["Senpai & Kouhai", "Master & Servant", "Opposites Attract"],
    tone: "Action/Adventure",
    status: "Completed",
    synopsis: "At Yurigaoka Girls' Academy, young warriors known as Lilies wield CHARM transformable weapons against monstrous invaders called Huge. Riri Hitotsuyanagi enrolls to form a Schutzengel (guardian angel) contract with troubled elite Yuyu Shirai.",
    famousQuote: "Yuyu-sama, I will fight by your side and never leave you in the dark alone.",
    coverImage: "https://media.kitsu.app/anime/poster_images/42598/large.jpg",
    pairing: "Riri Hitotsuyanagi x Yuyu Shirai",
    aliases: ["Assault Lily", "Bouquet", "RiriYuyu", "Schutzengel"]
  },
  {
    id: "saki",
    title: "Saki",
    romaji: "Saki",
    nativeTitle: "咲-Saki-",
    medium: "Anime",
    releaseYear: 2009,
    origin: "Japan",
    setting: "High School",
    tropes: ["Opposites Attract", "Enemies to Lovers", "Slow Burn"],
    tone: "Comedy",
    status: "Completed",
    synopsis: "Saki Miyanaga hates mahjong because of childhood family punishment, but possesses miraculous superhuman tile-reading instinct. Joining Kiyosumi High Club alongside national champion Nodoka Haramura, they aim for the inter-high crown.",
    famousQuote: "I will win this hand with a Rinshan Kaihou (win off a replacement tile)!",
    coverImage: "https://media.kitsu.app/anime/poster_images/4379/large.jpg",
    pairing: "Saki Miyanaga x Nodoka Haramura",
    aliases: ["Saki", "Saki Miyanaga", "Nodoka Haramura", "SakiNodo"]
  },
  {
    id: "k-on",
    title: "K-ON!",
    romaji: "K-ON!",
    nativeTitle: "けいおん!",
    medium: "Anime",
    releaseYear: 2009,
    origin: "Japan",
    setting: "High School",
    tropes: ["Idol/Music", "Childhood Friends", "Opposites Attract"],
    tone: "Sweet/Fluff",
    status: "Completed",
    synopsis: "Four girls rescue Sakuragaoka High's Light Music Club, forming After School Tea Time (Houkago Tea Time). Yui and Azusa's adorable senpai-kouhai bond and Mio and Ritsu's childhood friend love story defined a generation.",
    famousQuote: "Please don't graduate! Light music club wouldn't be light music club without all of us!",
    coverImage: "https://media.kitsu.app/anime/poster_images/4308/large.jpg",
    pairing: "Yui Hirasawa x Azusa Nakano / Ritsu Tainaka x Mio Akiyama",
    aliases: ["K-ON", "HTT", "Houkago Tea Time", "YuiAzusa", "Mitsu"]
  },
  {
    id: "yuki-yuna",
    title: "Yuki Yuna is a Hero",
    romaji: "Yuuki Yuuna wa Yuusha de Aru",
    nativeTitle: "結城友奈は勇者である",
    medium: "Anime",
    releaseYear: 2014,
    origin: "Japan",
    setting: "Fantasy/Magic",
    tropes: ["Opposites Attract", "Master & Servant", "Childhood Friends"],
    tone: "Dark/Psychological",
    status: "Completed",
    synopsis: "Middle schoolers in the Sanshu Middle School Hero Club fight otherworldly invaders called Vertex, bearing devastating bodily sacrifices (Mankai) while maintaining unbreakable emotional devotion to each other.",
    famousQuote: "Yuuna-chan... I'll sacrifice anything in this world, if it means you can live happily.",
    coverImage: "https://media.kitsu.app/anime/poster_images/8537/large.jpg",
    pairing: "Yuna Yuki x Mimori Togo",
    aliases: ["YuYuYu", "Yuki Yuna", "Mimori Togo", "Hero Club"]
  }
];

const seriesPath = path.resolve('src/data/yuriSeries.ts');
let seriesContent = fs.readFileSync(seriesPath, 'utf8');

// Filter out existing
const existingIds = new Set([...seriesContent.matchAll(/\"?id\"?:\s*['\"]([^'\"]+)['\"]/g)].map(m => m[1]));
const toAddSeries = newSeries.filter(s => !existingIds.has(s.id));

console.log('Series to add:', toAddSeries.length);

if (toAddSeries.length > 0) {
  const insertIndex = seriesContent.lastIndexOf('];');
  const formatted = toAddSeries.map(s => JSON.stringify(s, null, 2)).join(',\n  ');
  const updatedSeries = seriesContent.slice(0, insertIndex) + ',\n  ' + formatted + '\n];\n';
  fs.writeFileSync(seriesPath, updatedSeries, 'utf8');
  console.log('Successfully added series to yuriSeries.ts!');
}
