import fs from 'fs';

const NEW_CHARACTERS = [
  {
    id: 'sayaka-saeki',
    name: 'Sayaka Saeki',
    nativeName: '佐伯 沙弥香',
    seriesId: 'bloom-into-you',
    seriesTitle: 'Bloom Into You',
    role: 'Deuteragonist',
    hairColor: 'Brown',
    archetype: 'Kuudere',
    debutYear: 2015,
    quote: 'I loved Touko before you ever did. But watching you... I understand why she chose you.',
    wiki: 'yuri',
    wikiTitle: 'Sayaka_Saeki',
    pairingWith: 'Touko Nanami',
    aliases: ['Sayaka', 'Saeki Sayaka', 'Vice President']
  },
  {
    id: 'matsuri-mizusawa',
    name: 'Matsuri Mizusawa',
    nativeName: '水沢 まつり',
    seriesId: 'citrus',
    seriesTitle: 'Citrus',
    role: 'Rival',
    hairColor: 'Pink',
    archetype: 'Tsundere',
    debutYear: 2012,
    quote: 'Yuzu-oneechan belongs to me! I won\'t let that cold council president steal her.',
    wiki: 'yuri',
    wikiTitle: 'Matsuri_Mizusawa',
    pairingWith: 'Harumi Taniguchi',
    aliases: ['Matsuri', 'Mizusawa']
  },
  {
    id: 'harumi-taniguchi',
    name: 'Harumi Taniguchi',
    nativeName: '谷口 はるみ',
    seriesId: 'citrus',
    seriesTitle: 'Citrus',
    role: 'Deuteragonist',
    hairColor: 'Blonde',
    archetype: 'Genki',
    debutYear: 2012,
    quote: 'Relax, Yuzukko! Gyaru best friends stick together through thick and thin.',
    wiki: 'yuri',
    wikiTitle: 'Harumi_Taniguchi',
    pairingWith: 'Matsuri Mizusawa',
    aliases: ['Harumin', 'Taniguchi Harumi']
  },
  {
    id: 'ryo-yamada',
    name: 'Ryo Yamada',
    nativeName: '山田 リョウ',
    seriesId: 'bocchi-the-rock',
    seriesTitle: 'Bocchi the Rock!',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Kuudere',
    debutYear: 2017,
    quote: 'Abandoning your individuality is the same as abandoning your life.',
    wiki: 'bocchi-the-rock',
    wikiTitle: 'Ryo_Yamada',
    pairingWith: 'Nijika Ijichi',
    aliases: ['Ryo', 'Yamada Ryo', 'Weed Eater']
  },
  {
    id: 'nijika-ijichi',
    name: 'Nijika Ijichi',
    nativeName: '伊地知 虹夏',
    seriesId: 'bocchi-the-rock',
    seriesTitle: 'Bocchi the Rock!',
    role: 'Deuteragonist',
    hairColor: 'Blonde',
    archetype: 'Genki',
    debutYear: 2017,
    quote: 'You are our guitar hero, Bocchi-chan! You\'re the heart of Kessoku Band.',
    wiki: 'bocchi-the-rock',
    wikiTitle: 'Nijika_Ijichi',
    pairingWith: 'Ryo Yamada',
    aliases: ['Nijika', 'Ijichi Nijika', 'Dorito Angel']
  },
  {
    id: 'kikuri-hiroi',
    name: 'Kikuri Hiroi',
    nativeName: '廣井 きくり',
    seriesId: 'bocchi-the-rock',
    seriesTitle: 'Bocchi the Rock!',
    role: 'Deuteragonist',
    hairColor: 'Purple',
    archetype: 'Genki',
    debutYear: 2018,
    quote: 'A swig of sake before taking the stage clears away every speck of stage fright!',
    wiki: 'bocchi-the-rock',
    wikiTitle: 'Kikuri_Hiroi',
    pairingWith: 'Seika Ijichi',
    aliases: ['Kikuri', 'Hiroi Kikuri', 'SICK HACK Bassist']
  },
  {
    id: 'seika-ijichi',
    name: 'Seika Ijichi',
    nativeName: '伊地知 星歌',
    seriesId: 'bocchi-the-rock',
    seriesTitle: 'Bocchi the Rock!',
    role: 'Deuteragonist',
    hairColor: 'Blonde',
    archetype: 'Tsundere',
    debutYear: 2018,
    quote: 'Hmph, you girls still have a long way to go before you conquer STARRY.',
    wiki: 'bocchi-the-rock',
    wikiTitle: 'Seika_Ijichi',
    pairingWith: 'Kikuri Hiroi',
    aliases: ['Seika', 'Manager', 'Ijichi Seika']
  },
  {
    id: 'chuchu',
    name: 'Chuatury Panlunch',
    nativeName: 'チュアチュリー・パンランチ',
    seriesId: 'witch-from-mercury',
    seriesTitle: 'Mobile Suit Gundam: The Witch from Mercury',
    role: 'Deuteragonist',
    hairColor: 'Pink',
    archetype: 'Tsundere',
    debutYear: 2022,
    quote: 'Spacian bastards looking down on Earth House are gonna get a nail bat to the face!',
    wiki: 'gundam',
    wikiTitle: 'Chuatury_Panlunch',
    pairingWith: 'Nika Nanaura',
    aliases: ['Chuchu', 'Chuatury']
  },
  {
    id: 'nika-nanaura',
    name: 'Nika Nanaura',
    nativeName: 'ニカ・ナナウラ',
    seriesId: 'witch-from-mercury',
    seriesTitle: 'Mobile Suit Gundam: The Witch from Mercury',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Deredere',
    debutYear: 2022,
    quote: 'I want Earth and the Spacians to walk hand in hand without hatred.',
    wiki: 'gundam',
    wikiTitle: 'Nika_Nanaura',
    pairingWith: 'Chuatury Panlunch',
    aliases: ['Nika', 'Nanaura Nika']
  },
  {
    id: 'tomori-takamatsu',
    name: 'Tomori Takamatsu',
    nativeName: '高松 燈',
    seriesId: 'mygo',
    seriesTitle: 'BanG Dream! It\'s MyGO!!!!!',
    role: 'Protagonist',
    hairColor: 'Blue/Silver',
    archetype: 'Flustered Sweetheart',
    debutYear: 2023,
    quote: 'Even if we are lost, as long as we keep screaming together, we can become human.',
    wiki: 'bandori',
    wikiTitle: 'Takamatsu_Tomori',
    pairingWith: 'Anon Chihaya',
    aliases: ['Tomori', 'Takamatsu Tomori', 'Penguin Girl']
  },
  {
    id: 'anon-chihaya',
    name: 'Anon Chihaya',
    nativeName: '千早 愛音',
    seriesId: 'mygo',
    seriesTitle: 'BanG Dream! It\'s MyGO!!!!!',
    role: 'Deuteragonist',
    hairColor: 'Pink',
    archetype: 'Genki',
    debutYear: 2023,
    quote: 'I didn\'t start this band just to look cool anymore... I want to be with all of you!',
    wiki: 'bandori',
    wikiTitle: 'Chihaya_Anon',
    pairingWith: 'Tomori Takamatsu',
    aliases: ['Anon', 'Anon-chan', 'Chihaya Anon']
  },
  {
    id: 'soyo-nagasaki',
    name: 'Soyo Nagasaki',
    nativeName: '長崎 そよ',
    seriesId: 'mygo',
    seriesTitle: 'BanG Dream! It\'s MyGO!!!!!',
    role: 'Deuteragonist',
    hairColor: 'Brown',
    archetype: 'Yandere',
    debutYear: 2023,
    quote: 'Why did you play Haruhikage?! Everything I did was for CRYCHIC!',
    wiki: 'bandori',
    wikiTitle: 'Nagasaki_Soyo',
    pairingWith: 'Sakiko Togawa',
    aliases: ['Soyo', 'Nagasaki Soyo', 'Soyo-san']
  },
  {
    id: 'taki-shiina',
    name: 'Taki Shiina',
    nativeName: '椎名 立希',
    seriesId: 'mygo',
    seriesTitle: 'BanG Dream! It\'s MyGO!!!!!',
    role: 'Deuteragonist',
    hairColor: 'Black',
    archetype: 'Tsundere',
    debutYear: 2023,
    quote: 'Tomori\'s lyrics are everything to me. I won\'t let anyone ruin her songs.',
    wiki: 'bandori',
    wikiTitle: 'Shiina_Taki',
    pairingWith: 'Tomori Takamatsu',
    aliases: ['Taki', 'Ricky', 'Shiina Taki']
  },
  {
    id: 'sakiko-togawa',
    name: 'Sakiko Togawa',
    nativeName: '豊川 祥子',
    seriesId: 'mygo',
    seriesTitle: 'BanG Dream! It\'s MyGO!!!!!',
    role: 'Rival',
    hairColor: 'Blue/Silver',
    archetype: 'Ojou-sama',
    debutYear: 2023,
    quote: 'Forget the past. I will build Ave Mujica into a realm that reigns over fate itself.',
    wiki: 'bandori',
    wikiTitle: 'Togawa_Sakiko',
    pairingWith: 'Soyo Nagasaki',
    aliases: ['Sakiko', 'Saki', 'Togawa Sakiko', 'Oblivionis']
  },
  {
    id: 'raana-kaname',
    name: 'Raana Kaname',
    nativeName: '要 楽奈',
    seriesId: 'mygo',
    seriesTitle: 'BanG Dream! It\'s MyGO!!!!!',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Kuudere',
    debutYear: 2023,
    quote: 'I am a stray cat. I play guitar when I feel like it, and eat matcha parfait.',
    wiki: 'bandori',
    wikiTitle: 'Kaname_Raana',
    pairingWith: 'Tomori Takamatsu',
    aliases: ['Raana', 'Stray Cat', 'Kaname Raana']
  },
  {
    id: 'yukina-minato',
    name: 'Yukina Minato',
    nativeName: '湊 友希那',
    seriesId: 'bang-dream',
    seriesTitle: 'BanG Dream!',
    role: 'Protagonist',
    hairColor: 'Blue/Silver',
    archetype: 'Kuudere',
    debutYear: 2017,
    quote: 'Are you prepared to devote everything to Roselia? Lisa, stay by my side.',
    wiki: 'bandori',
    wikiTitle: 'Minato_Yukina',
    pairingWith: 'Lisa Imai',
    aliases: ['Yukina', 'Minato Yukina', 'Roselia Vocalist']
  },
  {
    id: 'lisa-imai',
    name: 'Lisa Imai',
    nativeName: '今井 リサ',
    seriesId: 'bang-dream',
    seriesTitle: 'BanG Dream!',
    role: 'Love Interest',
    hairColor: 'Brown',
    archetype: 'Deredere',
    debutYear: 2017,
    quote: 'Yukina, I promised since we were little kids that I\'d always back you up.',
    wiki: 'bandori',
    wikiTitle: 'Imai_Lisa',
    pairingWith: 'Yukina Minato',
    aliases: ['Lisa', 'Lisa-nee', 'Imai Lisa']
  },
  {
    id: 'sayo-hikawa',
    name: 'Sayo Hikawa',
    nativeName: '氷川 紗夜',
    seriesId: 'bang-dream',
    seriesTitle: 'BanG Dream!',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Tsundere',
    debutYear: 2017,
    quote: 'I cannot accept taking second place to my genius twin sister. I will perfect my craft.',
    wiki: 'bandori',
    wikiTitle: 'Hikawa_Sayo',
    pairingWith: 'Hina Hikawa',
    aliases: ['Sayo', 'Hikawa Sayo']
  },
  {
    id: 'hina-hikawa',
    name: 'Hina Hikawa',
    nativeName: '氷川 日菜',
    seriesId: 'bang-dream',
    seriesTitle: 'BanG Dream!',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Genki',
    debutYear: 2017,
    quote: 'Boppin\'! Everything is so fun when Onee-chan smiles at me!',
    wiki: 'bandori',
    wikiTitle: 'Hikawa_Hina',
    pairingWith: 'Sayo Hikawa',
    aliases: ['Hina', 'Hikawa Hina']
  },
  {
    id: 'nico-yazawa',
    name: 'Nico Yazawa',
    nativeName: '矢澤 にこ',
    seriesId: 'love-live-sip',
    seriesTitle: 'Love Live! School Idol Project',
    role: 'Deuteragonist',
    hairColor: 'Black',
    archetype: 'Tsundere',
    debutYear: 2013,
    quote: 'Nico Nico Nii~! The universe\'s number one school idol loves her precious Maki-chan.',
    wiki: 'love-live',
    wikiTitle: 'Nico_Yazawa',
    pairingWith: 'Maki Nishikino',
    aliases: ['Nico', 'Yazawa Nico', 'Nico-chan']
  },
  {
    id: 'maki-nishikino',
    name: 'Maki Nishikino',
    nativeName: '西木野 真姫',
    seriesId: 'love-live-sip',
    seriesTitle: 'Love Live! School Idol Project',
    role: 'Love Interest',
    hairColor: 'Red',
    archetype: 'Tsundere',
    debutYear: 2013,
    quote: 'I-it\'s not like I wrote this piano melody specifically for you, idiot!',
    wiki: 'love-live',
    wikiTitle: 'Maki_Nishikino',
    pairingWith: 'Nico Yazawa',
    aliases: ['Maki', 'Nishikino Maki', 'Maki-chan']
  },
  {
    id: 'eli-ayase',
    name: 'Eli Ayase',
    nativeName: '絢瀬 絵里',
    seriesId: 'love-live-sip',
    seriesTitle: 'Love Live! School Idol Project',
    role: 'Deuteragonist',
    hairColor: 'Blonde',
    archetype: 'Ojou-sama',
    debutYear: 2013,
    quote: 'Harasho! Nozomi, without your guidance, I never would have stepped onto this stage.',
    wiki: 'love-live',
    wikiTitle: 'Eli_Ayase',
    pairingWith: 'Nozomi Tojo',
    aliases: ['Eli', 'Ayase Eli', 'Elichika']
  },
  {
    id: 'nozomi-tojo',
    name: 'Nozomi Tojo',
    nativeName: '東條 希',
    seriesId: 'love-live-sip',
    seriesTitle: 'Love Live! School Idol Project',
    role: 'Deuteragonist',
    hairColor: 'Purple',
    archetype: 'Deredere',
    debutYear: 2013,
    quote: 'The tarot cards foretold this miracle. Muse was brought together by fate.',
    wiki: 'love-live',
    wikiTitle: 'Nozomi_Tojo',
    pairingWith: 'Eli Ayase',
    aliases: ['Nozomi', 'Tojo Nozomi', 'Nozo-chi']
  },
  {
    id: 'umi-sonoda',
    name: 'Umi Sonoda',
    nativeName: '園田 海未',
    seriesId: 'love-live-sip',
    seriesTitle: 'Love Live! School Idol Project',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Kuudere',
    debutYear: 2013,
    quote: 'Love Arrow Shoot! Shameless skirts aside, I will discipline our training routine.',
    wiki: 'love-live',
    wikiTitle: 'Umi_Sonoda',
    pairingWith: 'Kotori Minami',
    aliases: ['Umi', 'Sonoda Umi', 'Umi-chan']
  },
  {
    id: 'kotori-minami',
    name: 'Kotori Minami',
    nativeName: '南 ことり',
    seriesId: 'love-live-sip',
    seriesTitle: 'Love Live! School Idol Project',
    role: 'Deuteragonist',
    hairColor: 'Brown',
    archetype: 'Flustered Sweetheart',
    debutYear: 2013,
    quote: 'Chun chun~! I finished designing gorgeous new dresses for everyone to wear!',
    wiki: 'love-live',
    wikiTitle: 'Kotori_Minami',
    pairingWith: 'Umi Sonoda',
    aliases: ['Kotori', 'Minami Kotori', 'Kotobird']
  },
  {
    id: 'honoka-kosaka',
    name: 'Honoka Kosaka',
    nativeName: '高坂 穂乃果',
    seriesId: 'love-live-sip',
    seriesTitle: 'Love Live! School Idol Project',
    role: 'Protagonist',
    hairColor: 'Brown',
    archetype: 'Genki',
    debutYear: 2013,
    quote: 'Faitodayo! If we sing from the bottom of our hearts, Otonokizaka will never close!',
    wiki: 'love-live',
    wikiTitle: 'Honoka_Kosaka',
    pairingWith: 'Kotori Minami',
    aliases: ['Honoka', 'Kosaka Honoka', 'Honk']
  },
  {
    id: 'rin-hoshizora',
    name: 'Rin Hoshizora',
    nativeName: '星空 凛',
    seriesId: 'love-live-sip',
    seriesTitle: 'Love Live! School Idol Project',
    role: 'Deuteragonist',
    hairColor: 'Brown',
    archetype: 'Genki',
    debutYear: 2013,
    quote: 'Nya~! Can a tomboy like Rin really look cute in a bridal dress, Kayo-chin?',
    wiki: 'love-live',
    wikiTitle: 'Rin_Hoshizora',
    pairingWith: 'Hanayo Koizumi',
    aliases: ['Rin', 'Hoshizora Rin', 'Rin-chan']
  },
  {
    id: 'hanayo-koizumi',
    name: 'Hanayo Koizumi',
    nativeName: '小泉 花陽',
    seriesId: 'love-live-sip',
    seriesTitle: 'Love Live! School Idol Project',
    role: 'Deuteragonist',
    hairColor: 'Brown',
    archetype: 'Flustered Sweetheart',
    debutYear: 2013,
    quote: 'Somebody save me~! Rin-chan is the cutest idol in the whole wide world!',
    wiki: 'love-live',
    wikiTitle: 'Hanayo_Koizumi',
    pairingWith: 'Rin Hoshizora',
    aliases: ['Hanayo', 'Koizumi Hanayo', 'Kayo-chin']
  },
  {
    id: 'chika-takami',
    name: 'Chika Takami',
    nativeName: '高海 千歌',
    seriesId: 'love-live-sunshine',
    seriesTitle: 'Love Live! Sunshine!!',
    role: 'Protagonist',
    hairColor: 'Brown',
    archetype: 'Genki',
    debutYear: 2016,
    quote: 'Even normal monsters like us can shine like the sun over Numazu bay!',
    wiki: 'love-live',
    wikiTitle: 'Chika_Takami',
    pairingWith: 'Riko Sakurauchi',
    aliases: ['Chika', 'Takami Chika', 'Chika-chi']
  },
  {
    id: 'riko-sakurauchi',
    name: 'Riko Sakurauchi',
    nativeName: '桜内 梨子',
    seriesId: 'love-live-sunshine',
    seriesTitle: 'Love Live! Sunshine!!',
    role: 'Love Interest',
    hairColor: 'Red',
    archetype: 'Flustered Sweetheart',
    debutYear: 2016,
    quote: 'Chika-chan took my hand when the piano keys fell silent and gave me back my song.',
    wiki: 'love-live',
    wikiTitle: 'Riko_Sakurauchi',
    pairingWith: 'Chika Takami',
    aliases: ['Riko', 'Sakurauchi Riko', 'Riko-chan']
  },
  {
    id: 'kanan-matsuura',
    name: 'Kanan Matsuura',
    nativeName: '松浦 果南',
    seriesId: 'love-live-sunshine',
    seriesTitle: 'Love Live! Sunshine!!',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Prince-type',
    debutYear: 2016,
    quote: 'Let\'s dive together into the deep blue ocean. I\'ll always look after Dia and Mari.',
    wiki: 'love-live',
    wikiTitle: 'Kanan_Matsuura',
    pairingWith: 'Dia Kurosawa',
    aliases: ['Kanan', 'Matsuura Kanan']
  },
  {
    id: 'dia-kurosawa',
    name: 'Dia Kurosawa',
    nativeName: '黒澤 ダイヤ',
    seriesId: 'love-live-sunshine',
    seriesTitle: 'Love Live! Sunshine!!',
    role: 'Deuteragonist',
    hairColor: 'Black',
    archetype: 'Ojou-sama',
    debutYear: 2016,
    quote: 'Buu buu desu wa! As student council president, perfection is non-negotiable.',
    wiki: 'love-live',
    wikiTitle: 'Dia_Kurosawa',
    pairingWith: 'Kanan Matsuura',
    aliases: ['Dia', 'Kurosawa Dia', 'Dia-sama']
  },
  {
    id: 'yu-takasaki',
    name: 'Yu Takasaki',
    nativeName: '高咲 侑',
    seriesId: 'love-live-nijigasaki',
    seriesTitle: 'Love Live! Nijigasaki High School Idol Club',
    role: 'Protagonist',
    hairColor: 'Black',
    archetype: 'Genki',
    debutYear: 2020,
    quote: 'My heart won\'t stop pounding! I want to cheer for every idol with all my heart.',
    wiki: 'love-live',
    wikiTitle: 'Yu_Takasaki',
    pairingWith: 'Ayumu Uehara',
    aliases: ['Yu', 'Takasaki Yu', 'Yuu-chan']
  },
  {
    id: 'ayumu-uehara',
    name: 'Ayumu Uehara',
    nativeName: '上原 歩夢',
    seriesId: 'love-live-nijigasaki',
    seriesTitle: 'Love Live! Nijigasaki High School Idol Club',
    role: 'Love Interest',
    hairColor: 'Pink',
    archetype: 'Yandere',
    debutYear: 2020,
    quote: 'Yuu-chan is my only special person. You\'re not looking at other idols... are you?',
    wiki: 'love-live',
    wikiTitle: 'Ayumu_Uehara',
    pairingWith: 'Yu Takasaki',
    aliases: ['Ayumu', 'Uehara Ayumu', 'Ayu-pyon']
  },
  {
    id: 'setsuna-yuki',
    name: 'Setsuna Yuki',
    nativeName: '優木 せつ菜',
    seriesId: 'love-live-nijigasaki',
    seriesTitle: 'Love Live! Nijigasaki High School Idol Club',
    role: 'Deuteragonist',
    hairColor: 'Black',
    archetype: 'Genki',
    debutYear: 2020,
    quote: 'DIVE! into your passions! Let my fiery song light up the whole world!',
    wiki: 'love-live',
    wikiTitle: 'Setsuna_Yuki',
    pairingWith: 'Yu Takasaki',
    aliases: ['Setsuna', 'Nana Nakagawa', 'Yuki Setsuna']
  },
  {
    id: 'villhaze',
    name: 'Villhaze',
    nativeName: 'ヴィルヘイズ',
    seriesId: 'vexations-of-a-shut-in-vampire',
    seriesTitle: 'The Vexations of a Shut-In Vampire Princess',
    role: 'Love Interest',
    hairColor: 'Blue/Silver',
    archetype: 'Yandere',
    debutYear: 2020,
    quote: 'Komari-sama\'s lovely undergarments and divine aroma are my sole reason to exist.',
    wiki: 'yuri',
    wikiTitle: 'Villhaze',
    pairingWith: 'Terakomari Gandesblood',
    aliases: ['Vill', 'Villhaze']
  },
  {
    id: 'sumika-chibana',
    name: 'Sumika Chibana',
    nativeName: '知花 純加',
    seriesId: 'yuri-is-my-job',
    seriesTitle: 'Yuri Is My Job!',
    role: 'Deuteragonist',
    hairColor: 'Blonde',
    archetype: 'Tsundere',
    debutYear: 2016,
    quote: 'Playing the cool, aloof senpai Schwestern at Cafe Liebe is easier than facing love.',
    wiki: 'yuri',
    wikiTitle: 'Sumika_Chibana',
    pairingWith: 'Kanoko Mamiya',
    aliases: ['Sumika', 'Chibana Sumika', 'Schwester Sumika']
  },
  {
    id: 'kanoko-mamiya',
    name: 'Kanoko Mamiya',
    nativeName: '間宮 果乃子',
    seriesId: 'yuri-is-my-job',
    seriesTitle: 'Yuri Is My Job!',
    role: 'Deuteragonist',
    hairColor: 'Black',
    archetype: 'Kuudere',
    debutYear: 2016,
    quote: 'Hime has always been my angel. I won\'t let anyone see behind her mask except me.',
    wiki: 'yuri',
    wikiTitle: 'Kanoko_Mamiya',
    pairingWith: 'Sumika Chibana',
    aliases: ['Kanoko', 'Mamiya Kanoko']
  },
  {
    id: 'koyuki-honami',
    name: 'Koyuki Honami',
    nativeName: '帆波 小雪',
    seriesId: 'tropical-fish',
    seriesTitle: 'A Tropical Fish Yearns for Snow',
    role: 'Love Interest',
    hairColor: 'Blue/Silver',
    archetype: 'Ojou-sama',
    debutYear: 2017,
    quote: 'Everyone expects me to be a graceful salamander, but inside I am cold and lonely.',
    wiki: 'yuri',
    wikiTitle: 'Koyuki_Honami',
    pairingWith: 'Konatsu Amano',
    aliases: ['Koyuki', 'Honami Koyuki', 'Salamander Senpai']
  },
  {
    id: 'saki-miyanaga',
    name: 'Saki Miyanaga',
    nativeName: '宮永 咲',
    seriesId: 'saki',
    seriesTitle: 'Saki',
    role: 'Protagonist',
    hairColor: 'Pink',
    archetype: 'Flustered Sweetheart',
    debutYear: 2006,
    quote: 'Rinshan Kaihou! I only ever aimed for plus-minus zero until I met Nodoka-chan.',
    wiki: 'yuri',
    wikiTitle: 'Saki_Miyanaga',
    pairingWith: 'Nodoka Haramura',
    aliases: ['Saki', 'Miyanaga Saki', 'Mahjong Prodigy']
  },
  {
    id: 'nodoka-haramura',
    name: 'Nodoka Haramura',
    nativeName: '原村 和',
    seriesId: 'saki',
    seriesTitle: 'Saki',
    role: 'Love Interest',
    hairColor: 'Pink',
    archetype: 'Deredere',
    debutYear: 2006,
    quote: 'Digital mahjong calculates probability without miracles... but Saki-san is a true miracle.',
    wiki: 'yuri',
    wikiTitle: 'Nodoka_Haramura',
    pairingWith: 'Saki Miyanaga',
    aliases: ['Nodoka', 'Nodocchi', 'Haramura Nodoka']
  },
  {
    id: 'yuna-yuki',
    name: 'Yuna Yuki',
    nativeName: '結城 友奈',
    seriesId: 'yuuki-yuuna',
    seriesTitle: 'Yuki Yuna is a Hero',
    role: 'Protagonist',
    hairColor: 'Pink',
    archetype: 'Genki',
    debutYear: 2014,
    quote: 'Hero Club Creed Number One: Greet everyone cheerfully! Togo-san, I\'ll always protect you!',
    wiki: 'yuri',
    wikiTitle: 'Yuna_Yuki',
    pairingWith: 'Mimori Togo',
    aliases: ['Yuna', 'Yuki Yuna', 'Hero Club Leader']
  },
  {
    id: 'mimori-togo',
    name: 'Mimori Togo',
    nativeName: '東郷 美森',
    seriesId: 'yuuki-yuuna',
    seriesTitle: 'Yuki Yuna is a Hero',
    role: 'Love Interest',
    hairColor: 'Black',
    archetype: 'Yandere',
    debutYear: 2014,
    quote: 'If this world demands Yuna\'s sacrifice to survive, then I will destroy this world myself.',
    wiki: 'yuri',
    wikiTitle: 'Mimori_Togo',
    pairingWith: 'Yuna Yuki',
    aliases: ['Togo', 'Mimori Togo', 'Washio Sumi']
  },
  {
    id: 'yoshika-miyafuji',
    name: 'Yoshika Miyafuji',
    nativeName: '宮藤 芳佳',
    seriesId: 'strike-witches',
    seriesTitle: 'Strike Witches',
    role: 'Protagonist',
    hairColor: 'Brown',
    archetype: 'Genki',
    debutYear: 2008,
    quote: 'I want to protect everyone\'s smiles with my healing magic and Striker unit!',
    wiki: 'yuri',
    wikiTitle: 'Yoshika_Miyafuji',
    pairingWith: 'Mio Sakamoto',
    aliases: ['Yoshika', 'Miyafuji Yoshika', 'Striker Ace']
  },
  {
    id: 'mio-sakamoto',
    name: 'Mio Sakamoto',
    nativeName: '坂本 美緒',
    seriesId: 'strike-witches',
    seriesTitle: 'Strike Witches',
    role: 'Deuteragonist',
    hairColor: 'Black',
    archetype: 'Prince-type',
    debutYear: 2008,
    quote: 'With my magic eye and katana Reppuuzan, no Neuroi shall pierce our defense line.',
    wiki: 'yuri',
    wikiTitle: 'Mio_Sakamoto',
    pairingWith: 'Yoshika Miyafuji',
    aliases: ['Mio', 'Major Sakamoto', 'Sakamoto Mio']
  },
  {
    id: 'tokai-teio',
    name: 'Tokai Teio',
    nativeName: 'トウカイテイオー',
    seriesId: 'uma-musume',
    seriesTitle: 'Uma Musume: Pretty Derby',
    role: 'Protagonist',
    hairColor: 'Brown',
    archetype: 'Genki',
    debutYear: 2018,
    quote: 'Teio step! I won\'t ever give up on my dream to run alongside McQueen at the Arima Kinen!',
    wiki: 'yuri',
    wikiTitle: 'Tokai_Teio',
    pairingWith: 'Mejiro McQueen',
    aliases: ['Teio', 'Tokai Teio', 'Miracle Derby Runner']
  },
  {
    id: 'mejiro-mcqueen',
    name: 'Mejiro McQueen',
    nativeName: 'メジロマックイーン',
    seriesId: 'uma-musume',
    seriesTitle: 'Uma Musume: Pretty Derby',
    role: 'Love Interest',
    hairColor: 'Blue/Silver',
    archetype: 'Ojou-sama',
    debutYear: 2018,
    quote: 'The pride of the Mejiro lineage demands unmatched endurance. Teio, you are my greatest rival.',
    wiki: 'yuri',
    wikiTitle: 'Mejiro_McQueen',
    pairingWith: 'Tokai Teio',
    aliases: ['McQueen', 'Mejiro McQueen', 'Parfait Queen']
  },
  {
    id: 'special-week',
    name: 'Special Week',
    nativeName: 'スペシャルウィーク',
    seriesId: 'uma-musume',
    seriesTitle: 'Uma Musume: Pretty Derby',
    role: 'Protagonist',
    hairColor: 'Brown',
    archetype: 'Flustered Sweetheart',
    debutYear: 2018,
    quote: 'I promised my country mothers that I\'d become Japan\'s number one horse girl! Suzuka-san, look at me!',
    wiki: 'yuri',
    wikiTitle: 'Special_Week',
    pairingWith: 'Silence Suzuka',
    aliases: ['Spe-chan', 'Special Week']
  },
  {
    id: 'silence-suzuka',
    name: 'Silence Suzuka',
    nativeName: 'サイレンススズカ',
    seriesId: 'uma-musume',
    seriesTitle: 'Uma Musume: Pretty Derby',
    role: 'Love Interest',
    hairColor: 'Brown',
    archetype: 'Kuudere',
    debutYear: 2018,
    quote: 'I run because the view of the open turf ahead feels like true freedom. Thank you for running with me, Spe-chan.',
    wiki: 'yuri',
    wikiTitle: 'Silence_Suzuka',
    pairingWith: 'Special Week',
    aliases: ['Suzuka', 'Silence Suzuka', 'Shadow Runner']
  },
  {
    id: 'sayaka-miki',
    name: 'Sayaka Miki',
    nativeName: '美樹 さやか',
    seriesId: 'madoka-magica',
    seriesTitle: 'Puella Magi Madoka Magica',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Genki',
    debutYear: 2011,
    quote: 'I made a contract to heal the one I loved... and I don\'t regret becoming a magical girl for a single second!',
    wiki: 'madoka',
    wikiTitle: 'Sayaka_Miki',
    pairingWith: 'Kyoko Sakura',
    aliases: ['Sayaka', 'Miki Sayaka', 'Oktavia']
  },
  {
    id: 'kyoko-sakura',
    name: 'Kyoko Sakura',
    nativeName: '佐倉 杏子',
    seriesId: 'madoka-magica',
    seriesTitle: 'Puella Magi Madoka Magica',
    role: 'Deuteragonist',
    hairColor: 'Red',
    archetype: 'Tsundere',
    debutYear: 2011,
    quote: 'Don\'t worry, Sayaka... It sucks being alone, right? I\'ll be right there with you to the very end.',
    wiki: 'madoka',
    wikiTitle: 'Kyoko_Sakura',
    pairingWith: 'Sayaka Miki',
    aliases: ['Kyoko', 'Sakura Kyoko', 'Pocky Eater']
  },
  {
    id: 'mami-tomoe',
    name: 'Mami Tomoe',
    nativeName: '巴 マミ',
    seriesId: 'madoka-magica',
    seriesTitle: 'Puella Magi Madoka Magica',
    role: 'Deuteragonist',
    hairColor: 'Blonde',
    archetype: 'Ojou-sama',
    debutYear: 2011,
    quote: 'Tiro Finale! If I\'m with you, I\'m not afraid of anything anymore.',
    wiki: 'madoka',
    wikiTitle: 'Mami_Tomoe',
    pairingWith: 'Madoka Kaname',
    aliases: ['Mami', 'Tomoe Mami', 'Mami-san']
  },
  {
    id: 'hibiki-tachibana',
    name: 'Hibiki Tachibana',
    nativeName: '立花 響',
    seriesId: 'symphogear',
    seriesTitle: 'Senki Zesshou Symphogear',
    role: 'Protagonist',
    hairColor: 'Brown',
    archetype: 'Genki',
    debutYear: 2012,
    quote: 'I sing my Gungnir melody to connect hands with everyone! Miku, I\'m home!',
    wiki: 'symphogear',
    wikiTitle: 'Hibiki_Tachibana',
    pairingWith: 'Miku Kohinata',
    aliases: ['Hibiki', 'Tachibana Hibiki', 'Bikki']
  },
  {
    id: 'miku-kohinata',
    name: 'Miku Kohinata',
    nativeName: '小日向 未来',
    seriesId: 'symphogear',
    seriesTitle: 'Senki Zesshou Symphogear',
    role: 'Love Interest',
    hairColor: 'Black',
    archetype: 'Deredere',
    debutYear: 2012,
    quote: 'Hibiki is my sun. No matter how deep into the darkness you fall, I will reach out and hold you.',
    wiki: 'symphogear',
    wikiTitle: 'Miku_Kohinata',
    pairingWith: 'Hibiki Tachibana',
    aliases: ['Miku', 'Kohinata Miku', 'Shenshoujing']
  },
  {
    id: 'chris-yukine',
    name: 'Chris Yukine',
    nativeName: '雪音 クリス',
    seriesId: 'symphogear',
    seriesTitle: 'Senki Zesshou Symphogear',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Tsundere',
    debutYear: 2012,
    quote: 'Megadeth Party! S-shut up, senpai! It\'s not like I wanted you to hear my new song!',
    wiki: 'symphogear',
    wikiTitle: 'Chris_Yukine',
    pairingWith: 'Tsubasa Kazanari',
    aliases: ['Chris', 'Yukine Chris', 'Zenbu']
  },
  {
    id: 'tsubasa-kazanari',
    name: 'Tsubasa Kazanari',
    nativeName: '風鳴 翼',
    seriesId: 'symphogear',
    seriesTitle: 'Senki Zesshou Symphogear',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Prince-type',
    debutYear: 2012,
    quote: 'I am a sword wielded for the sake of the battlefield. Maria, ignite your soul!',
    wiki: 'symphogear',
    wikiTitle: 'Tsubasa_Kazanari',
    pairingWith: 'Maria Cadenzavna Eve',
    aliases: ['Tsubasa', 'Kazanari Tsubasa', 'Sword Maiden']
  },
  {
    id: 'maria-cadenzavna-eve',
    name: 'Maria Cadenzavna Eve',
    nativeName: 'マリア・カデンツァヴナ・イヴ',
    seriesId: 'symphogear',
    seriesTitle: 'Senki Zesshou Symphogear',
    role: 'Deuteragonist',
    hairColor: 'Pink',
    archetype: 'Kuudere',
    debutYear: 2013,
    quote: 'Even if my hands are stained, I will carry the dreams of everyone we lost into tomorrow.',
    wiki: 'symphogear',
    wikiTitle: 'Maria_Cadenzavna_Eve',
    pairingWith: 'Tsubasa Kazanari',
    aliases: ['Maria', 'Maria Cadenzavna Eve']
  },
  {
    id: 'karen-aijo',
    name: 'Karen Aijo',
    nativeName: '愛城 華恋',
    seriesId: 'revue-starlight',
    seriesTitle: 'Revue Starlight',
    role: 'Protagonist',
    hairColor: 'Brown',
    archetype: 'Genki',
    debutYear: 2018,
    quote: 'Position Zero! Hikari-chan and I will stand on the starlight stage together forever!',
    wiki: 'revuestarlight',
    wikiTitle: 'Karen_Aijo',
    pairingWith: 'Hikari Kagura',
    aliases: ['Karen', 'Aijo Karen']
  },
  {
    id: 'hikari-kagura',
    name: 'Hikari Kagura',
    nativeName: '神楽 ひかり',
    seriesId: 'revue-starlight',
    seriesTitle: 'Revue Starlight',
    role: 'Love Interest',
    hairColor: 'Blue/Silver',
    archetype: 'Kuudere',
    debutYear: 2018,
    quote: 'I took your dagger and locked my feelings away... because I never wanted your shine to fade.',
    wiki: 'revuestarlight',
    wikiTitle: 'Hikari_Kagura',
    pairingWith: 'Karen Aijo',
    aliases: ['Hikari', 'Kagura Hikari']
  },
  {
    id: 'maya-tendo',
    name: 'Maya Tendo',
    nativeName: '天堂 真矢',
    seriesId: 'revue-starlight',
    seriesTitle: 'Revue Starlight',
    role: 'Rival',
    hairColor: 'Brown',
    archetype: 'Ojou-sama',
    debutYear: 2018,
    quote: 'This is Maya Tendo. Claudine, you are the only one worthy to chase my throne.',
    wiki: 'revuestarlight',
    wikiTitle: 'Maya_Tendo',
    pairingWith: 'Claudine Saijo',
    aliases: ['Maya', 'Tendo Maya', 'This is Maya Tendo']
  },
  {
    id: 'claudine-saijo',
    name: 'Claudine Saijo',
    nativeName: '西條 クロディーヌ',
    seriesId: 'revue-starlight',
    seriesTitle: 'Revue Starlight',
    role: 'Deuteragonist',
    hairColor: 'Blonde',
    archetype: 'Tsundere',
    debutYear: 2018,
    quote: 'C\'est moi, la star! Maya, I will never stop reaching until I defeat you and take your crown!',
    wiki: 'revuestarlight',
    wikiTitle: 'Claudine_Saijo',
    pairingWith: 'Maya Tendo',
    aliases: ['Claudine', 'Kuro', 'Saijo Claudine']
  },
  {
    id: 'kaoruko-hanayagi',
    name: 'Kaoruko Hanayagi',
    nativeName: '花柳 香子',
    seriesId: 'revue-starlight',
    seriesTitle: 'Revue Starlight',
    role: 'Deuteragonist',
    hairColor: 'Pink',
    archetype: 'Tsundere',
    debutYear: 2018,
    quote: 'Futahan! Why won\'t you carry my bag and stay behind me like we always did in Kyoto?',
    wiki: 'revuestarlight',
    wikiTitle: 'Kaoruko_Hanayagi',
    pairingWith: 'Futaba Isurugi',
    aliases: ['Kaoruko', 'Hanayagi Kaoruko']
  },
  {
    id: 'futaba-isurugi',
    name: 'Futaba Isurugi',
    nativeName: '石動 双葉',
    seriesId: 'revue-starlight',
    seriesTitle: 'Revue Starlight',
    role: 'Deuteragonist',
    hairColor: 'Brown',
    archetype: 'Prince-type',
    debutYear: 2018,
    quote: 'I rev my motorcycle and ride on ahead because I want to be someone Kaoruko is proud of.',
    wiki: 'revuestarlight',
    wikiTitle: 'Futaba_Isurugi',
    pairingWith: 'Kaoruko Hanayagi',
    aliases: ['Futaba', 'Isurugi Futaba']
  },
  {
    id: 'nana-daiba',
    name: 'Nana Daiba',
    nativeName: '大場 なな',
    seriesId: 'revue-starlight',
    seriesTitle: 'Revue Starlight',
    role: 'Deuteragonist',
    hairColor: 'Blonde',
    archetype: 'Yandere',
    debutYear: 2018,
    quote: 'Wakarimasu. If this dazzling stage must end, then I will repeat our 99th festival forever.',
    wiki: 'revuestarlight',
    wikiTitle: 'Nana_Daiba',
    pairingWith: 'Junna Hoshimi',
    aliases: ['Banana', 'Nana', 'Daiba Nana']
  },
  {
    id: 'junna-hoshimi',
    name: 'Junna Hoshimi',
    nativeName: '星見 純那',
    seriesId: 'revue-starlight',
    seriesTitle: 'Revue Starlight',
    role: 'Deuteragonist',
    hairColor: 'Blue/Silver',
    archetype: 'Kuudere',
    debutYear: 2018,
    quote: 'A star cannot shine without striving against destiny! Nana, let go of the past!',
    wiki: 'revuestarlight',
    wikiTitle: 'Junna_Hoshimi',
    pairingWith: 'Nana Daiba',
    aliases: ['Junna', 'Hoshimi Junna']
  },
  {
    id: 'yuko-yoshida',
    name: 'Yuko Yoshida',
    nativeName: '吉田 優子',
    seriesId: 'machikado-mazoku',
    seriesTitle: 'The Demon Girl Next Door',
    role: 'Protagonist',
    hairColor: 'Brown',
    archetype: 'Flustered Sweetheart',
    debutYear: 2014,
    quote: 'Don\'t think you\'ve won, magical girl Momo! The Dark Clan shall rise again!',
    wiki: 'machikado-mazoku',
    wikiTitle: 'Yuko_Yoshida',
    pairingWith: 'Momo Chiyoda',
    aliases: ['Shamiko', 'Shadow Mistress Yuko', 'Yoshida Yuko']
  },
  {
    id: 'momo-chiyoda',
    name: 'Momo Chiyoda',
    nativeName: '千代田 桃',
    seriesId: 'machikado-mazoku',
    seriesTitle: 'The Demon Girl Next Door',
    role: 'Love Interest',
    hairColor: 'Pink',
    archetype: 'Kuudere',
    debutYear: 2014,
    quote: 'Shamiko is hopelessly weak... I have to feed her proper protein every single day.',
    wiki: 'machikado-mazoku',
    wikiTitle: 'Momo_Chiyoda',
    pairingWith: 'Yuko Yoshida',
    aliases: ['Momo', 'Chiyoda Momo', 'Magical Girl Momo']
  },
  {
    id: 'nagisa-aoi',
    name: 'Nagisa Aoi',
    nativeName: '蒼井 渚砂',
    seriesId: 'strawberry-panic',
    seriesTitle: 'Strawberry Panic',
    role: 'Protagonist',
    hairColor: 'Red',
    archetype: 'Flustered Sweetheart',
    debutYear: 2006,
    quote: 'When Shizuma-sama looked into my eyes on Astraea Hill, my whole world stood still.',
    wiki: 'strawberrypanic',
    wikiTitle: 'Nagisa_Aoi',
    pairingWith: 'Shizuma Hanazono',
    aliases: ['Nagisa', 'Aoi Nagisa']
  },
  {
    id: 'shizuma-hanazono',
    name: 'Shizuma Hanazono',
    nativeName: '花園 静馬',
    seriesId: 'strawberry-panic',
    seriesTitle: 'Strawberry Panic',
    role: 'Love Interest',
    hairColor: 'Blue/Silver',
    archetype: 'Prince-type',
    debutYear: 2006,
    quote: 'The Etoile holds the hearts of all three academies, yet mine yearns only for you.',
    wiki: 'strawberrypanic',
    wikiTitle: 'Shizuma_Hanazono',
    pairingWith: 'Nagisa Aoi',
    aliases: ['Shizuma', 'Etoile', 'Hanazono Shizuma']
  },
  {
    id: 'yvonne-smollett',
    name: 'Yvonne Smollett',
    nativeName: 'イヴォンヌ・スモレット',
    seriesId: 'please-bully-me-miss-villainess',
    seriesTitle: 'Please Bully Me, Miss Villainess!',
    role: 'Protagonist',
    hairColor: 'Blonde',
    archetype: 'Tsundere',
    debutYear: 2021,
    quote: 'System, why do all my villainess bully quests end up pampering Elsa instead?!',
    wiki: 'yuri',
    wikiTitle: 'Yvonne_Smollett',
    pairingWith: 'Elsa Dorothy',
    aliases: ['Yvonne', 'Evangeline', 'Lady Smollett']
  },
  {
    id: 'elsa-dorothy',
    name: 'Elsa Dorothy',
    nativeName: 'エルサ・ドロシー',
    seriesId: 'please-bully-me-miss-villainess',
    seriesTitle: 'Please Bully Me, Miss Villainess!',
    role: 'Love Interest',
    hairColor: 'Blue/Silver',
    archetype: 'Deredere',
    debutYear: 2021,
    quote: 'Lady Yvonne is so kind and gentle... I love every single time she bullies me!',
    wiki: 'yuri',
    wikiTitle: 'Elsa_Dorothy',
    pairingWith: 'Yvonne Smollett',
    aliases: ['Elsa', 'Elsa Dorothy']
  },
  {
    id: 'himari-kino',
    name: 'Himari Kino',
    nativeName: '木野 ひまり',
    seriesId: 'whispering-you-a-love-song',
    seriesTitle: 'Whispering You a Love Song',
    role: 'Protagonist',
    hairColor: 'Brown',
    archetype: 'Deredere',
    debutYear: 2019,
    quote: 'I fell in love at first sight with your music, Yori-senpai! You are my idol!',
    wiki: 'yuri',
    wikiTitle: 'Himari_Kino',
    pairingWith: 'Yori Asanagi',
    aliases: ['Himari', 'Kino Himari', 'Hima-chan']
  },
  {
    id: 'yori-asanagi',
    name: 'Yori Asanagi',
    nativeName: '朝凪 依',
    seriesId: 'whispering-you-a-love-song',
    seriesTitle: 'Whispering You a Love Song',
    role: 'Love Interest',
    hairColor: 'Blue/Silver',
    archetype: 'Kuudere',
    debutYear: 2019,
    quote: 'You said you fell in love at first sight... but my love is romantic love, Himari.',
    wiki: 'yuri',
    wikiTitle: 'Yori_Asanagi',
    pairingWith: 'Himari Kino',
    aliases: ['Yori', 'Asanagi Yori', 'SSGIRLS Vocalist']
  }
];

async function fetchAvatar(char) {
  let domain = 'yuri.fandom.com';
  if (char.wiki === 'bocchi-the-rock') domain = 'bocchi-the-rock.fandom.com';
  else if (char.wiki === 'gundam') domain = 'gundam.fandom.com';
  else if (char.wiki === 'bandori') domain = 'bandori.fandom.com';
  else if (char.wiki === 'love-live') domain = 'love-live.fandom.com';
  else if (char.wiki === 'madoka') domain = 'madoka.fandom.com';
  else if (char.wiki === 'symphogear') domain = 'symphogear.fandom.com';
  else if (char.wiki === 'revuestarlight') domain = 'revuestarlight.fandom.com';
  else if (char.wiki === 'machikado-mazoku') domain = 'machikado-mazoku.fandom.com';
  else if (char.wiki === 'strawberrypanic') domain = 'strawberrypanic.fandom.com';

  const url = `https://${domain}/api.php?action=query&titles=${encodeURIComponent(char.wikiTitle)}&prop=pageimages&format=json&pithumbsize=400`;
  const res = await fetch(url);
  const data = await res.json();
  const page = Object.values(data.query?.pages || {})[0];
  const thumb = page?.thumbnail?.source;
  if (!thumb) {
    throw new Error(`Failed to get avatar for ${char.id} (${char.wikiTitle} on ${domain})`);
  }
  return thumb;
}

async function run() {
  console.log(`Starting avatar verification for ${NEW_CHARACTERS.length} characters...`);
  const finalCharacters = [];

  for (let i = 0; i < NEW_CHARACTERS.length; i++) {
    const c = NEW_CHARACTERS[i];
    try {
      const avatarUrl = await fetchAvatar(c);
      finalCharacters.push({
        id: c.id,
        name: c.name,
        nativeName: c.nativeName,
        seriesId: c.seriesId,
        seriesTitle: c.seriesTitle,
        role: c.role,
        hairColor: c.hairColor,
        archetype: c.archetype,
        debutYear: c.debutYear,
        quote: c.quote,
        avatar: avatarUrl,
        pairingWith: c.pairingWith,
        aliases: c.aliases
      });
      console.log(`[${i + 1}/${NEW_CHARACTERS.length}] OK: ${c.name} (${c.id})`);
    } catch (e) {
      console.error(`ERROR on ${c.id}: ${e.message}`);
      process.exit(1);
    }
    await new Promise(r => setTimeout(r, 100));
  }

  fs.writeFileSync('scripts/verified_new_characters.json', JSON.stringify(finalCharacters, null, 2));
  console.log(`Done! Saved ${finalCharacters.length} verified characters.`);
}

run();
