import fs from 'fs';

const newSeriesDefs = [
  {
    id: 'yuri-is-my-job',
    title: 'Yuri Is My Job!',
    romaji: 'Watashi no Yuri wa Oshigoto desu!',
    nativeTitle: '私の百合はお仕事です！',
    medium: 'Anime',
    releaseYear: 2023,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Opposites Attract', 'Master & Servant', 'Enemies to Lovers'],
    tone: 'Drama/Angst',
    status: 'Ongoing',
    synopsis: 'Hime Shiraki cares deeply about maintaining her pristine, flawless persona. After accidentally injuring cafe manager Mai, she is forced to work at Cafe Liebe, a themed salon where waitresses act like refined maiden academy students.',
    famousQuote: 'In this salon, our love is just an act... or is it?',
    pairing: 'Hime Shiraki x Yano Mitsuki',
    aliases: ['Watashi no Yuri wa Oshigoto desu', 'Cafe Liebe', 'Hime', 'Yano', 'Yurigoto'],
    kitsuType: 'anime',
    searchQuery: 'Watashi no Yuri wa Oshigoto desu!'
  },
  {
    id: 'sailor-moon-s',
    title: 'Sailor Moon S (Haruka & Michiru)',
    romaji: 'Bishoujo Senshi Sailor Moon S',
    nativeTitle: '美少女戦士セーラームーンS',
    medium: 'Anime',
    releaseYear: 1994,
    origin: 'Japan',
    setting: 'Fantasy/Magic',
    tropes: ['Opposites Attract', 'Childhood Friends', 'Slow Burn'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'The legendary romance between Sailor Uranus (Haruka Tenoh) and Sailor Neptune (Michiru Kaioh) that defined yuri representation in 90s anime. Bound by fate, music, and eternal devotion, they protect the cosmos together.',
    famousQuote: 'A world without Haruka is not a world worth saving.',
    pairing: 'Haruka Tenoh x Michiru Kaioh',
    aliases: ['Sailor Uranus', 'Sailor Neptune', 'Haruka Michiru', 'Sailor Moon'],
    kitsuType: 'anime',
    searchQuery: 'Sailor Moon S'
  },
  {
    id: 'mai-hime',
    title: 'Mai-HiME (Shizuru & Natsuki)',
    romaji: 'Mai-HiME',
    nativeTitle: '舞-HiME',
    medium: 'Anime',
    releaseYear: 2004,
    origin: 'Japan',
    setting: 'Fantasy/Magic',
    tropes: ['Senpai & Kouhai', 'Enemies to Lovers', 'Opposites Attract'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'At Fuka Academy, female warriors called HiME fight deadly Orphans with materialized weapons and robotic Child summons. Shizuru Fujino harbors a dangerously consuming devotion for her aloof junior, Natsuki Kuga.',
    famousQuote: 'Even if the world turns to ash, I will love you, Natsuki.',
    pairing: 'Shizuru Fujino x Natsuki Kuga',
    aliases: ['Mai Hime', 'Shizuru Natsuki', 'ShizNat', 'Sunrise'],
    kitsuType: 'anime',
    searchQuery: 'Mai-HiME'
  },
  {
    id: 'happy-sugar-life',
    title: 'Happy Sugar Life',
    romaji: 'Happy Sugar Life',
    nativeTitle: 'ハッピーシュガーライフ',
    medium: 'Anime',
    releaseYear: 2018,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Roommates', 'Age Gap'],
    tone: 'Dark/Psychological',
    status: 'Completed',
    synopsis: 'High schooler Matsuzaka Satou was known for being promiscuous until she met the pure young orphan Shio Koube. Believing she has finally discovered true love, Satou will commit kidnapping and even murder to protect their sweet life together.',
    famousQuote: 'My sweet, sweet sugar life... no one can take Shio from me.',
    pairing: 'Satou Matsuzaka x Shio Koube',
    aliases: ['Happy Sugar Life', 'Satou', 'Shio', 'Yandere Yuri'],
    kitsuType: 'anime',
    searchQuery: 'Happy Sugar Life'
  },
  {
    id: 'netsuzou-trap',
    title: 'Netsuzou Trap -NTR-',
    romaji: 'Netsuzou Trap -NTR-',
    nativeTitle: '捏造トラップ-NTR-',
    medium: 'Anime',
    releaseYear: 2017,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Childhood Friends', 'Enemies to Lovers', 'Love Triangle'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Yuma gets her first boyfriend and asks her experienced childhood friend Hotaru for double-date advice. Hotaru begins giving her scandalous "practice" kisses in secret, leading Yuma into an obsessive web of forbidden temptation.',
    famousQuote: 'Don\'t pretend you don\'t like doing this with me more than him.',
    pairing: 'Yuma Okazaki x Hotaru Mizushina',
    aliases: ['Netsuzou Trap', 'NTR Yuri', 'Yuma Hotaru', 'Naoko Kodama'],
    kitsuType: 'anime',
    searchQuery: 'Netsuzou Trap'
  },
  {
    id: 'mygo',
    title: 'BanG Dream! It\'s MyGO!!!!!',
    romaji: 'BanG Dream! It\'s MyGO!!!!!',
    nativeTitle: 'BanG Dream! It\'s MyGO!!!!!',
    medium: 'Anime',
    releaseYear: 2023,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Enemies to Lovers', 'Slow Burn'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Following the painful collapse of the band CRYCHIC, socially anxious vocalist Tomori Takamatsu and transfer student Anon Chihaya form a new rock band. Intense teenage resentment, longing, and heavy emotional entanglements clash.',
    famousQuote: 'Why did you play Haruhikage?!',
    pairing: 'Tomori Takamatsu x Anon Chihaya / Soyo x Sakiko',
    aliases: ['MyGO', 'Its MyGO', 'Anon', 'Tomori', 'Soyo Nagasaki', 'Haruhikage'],
    kitsuType: 'anime',
    searchQuery: 'BanG Dream! It\'s MyGO!!!!!'
  },
  {
    id: 'bang-dream',
    title: 'BanG Dream!',
    romaji: 'BanG Dream!',
    nativeTitle: 'バンドリ！',
    medium: 'Anime',
    releaseYear: 2017,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Childhood Friends'],
    tone: 'Sweet/Fluff',
    status: 'Ongoing',
    synopsis: 'Kasumi Toyama searches for the sparkling, heart-pounding sensation of the "Star Beat". Gathering friends to form the girls band Poppin\'Party, she forms profound ties with tsundere keyboardist Arisa Ichigaya.',
    famousQuote: 'Let\'s find the star beat together, Arisa!',
    pairing: 'Kasumi Toyama x Arisa Ichigaya',
    aliases: ['Bandori', 'Poppin Party', 'Roselia', 'Kasumi Arisa'],
    kitsuType: 'anime',
    searchQuery: 'BanG Dream!'
  },
  {
    id: 'love-live-sip',
    title: 'Love Live! School Idol Project',
    romaji: 'Love Live! School Idol Project',
    nativeTitle: 'ラブライブ！ School idol project',
    medium: 'Anime',
    releaseYear: 2013,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Childhood Friends'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Honoka Kosaka forms the school idol group \u03bc\'s (Muse) to save Otonokizaka High from closing down. Among the members blossom legendary ships, particularly student council president Eli Ayase and tarot-loving Nozomi Tojo.',
    famousQuote: 'Nozomi, power inject! We belong together in \u03bc\'s.',
    pairing: 'Eli Ayase x Nozomi Tojo / Nico x Maki',
    aliases: ['Love Live', 'NozoEli', 'NicoMaki', 'Muse', 'Otonokizaka'],
    kitsuType: 'anime',
    searchQuery: 'Love Live! School Idol Project'
  },
  {
    id: 'love-live-sunshine',
    title: 'Love Live! Sunshine!!',
    romaji: 'Love Live! Sunshine!!',
    nativeTitle: 'ラブライブ！サンシャイン!!',
    medium: 'Anime',
    releaseYear: 2016,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Childhood Friends', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'In seaside Uchiura, Chika Takami founds the school idol group Aqours. Intense bonds form between childhood friends Kanan and Dia, as well as the deep emotional connection between fallen angel Yoshiko and Hanamaru.',
    famousQuote: 'Step zero to one! We will shine together, no matter how small our town is.',
    pairing: 'Chika x Riko / Kanan x Dia / Yoshiko x Hanamaru',
    aliases: ['Love Live Sunshine', 'Aqours', 'Chika Riko', 'YoshiMaru', 'KananMari'],
    kitsuType: 'anime',
    searchQuery: 'Love Live! Sunshine!!'
  },
  {
    id: 'love-live-nijigasaki',
    title: 'Love Live! Nijigasaki High School Idol Club',
    romaji: 'Love Live! Nijigasaki Gakuen School Idol Doukoukai',
    nativeTitle: 'ラブライブ！虹ヶ咲学園スクールアイドル同好会',
    medium: 'Anime',
    releaseYear: 2020,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Childhood Friends', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Childhood friends Yuu Takasaki and Ayumu Uehara enter Nijigasaki High and resurrect the school idol club. When Yuu becomes inspired by all the diverse idol girls, Ayumu\'s intense, possessive feelings surface in unforgettable melodrama.',
    famousQuote: 'Yuu-chan... why aren\'t you looking only at me anymore?',
    pairing: 'Yuu Takasaki x Ayumu Uehara',
    aliases: ['Nijigasaki', 'NijiGaku', 'Yuu Ayumu', 'Yuu-chan'],
    kitsuType: 'anime',
    searchQuery: 'Love Live! Nijigasaki'
  },
  {
    id: 'tropical-fish',
    title: 'A Tropical Fish Yearns for Snow',
    romaji: 'Nettaigyo wa Yuki ni Kogareru',
    nativeTitle: '熱帯魚は雪に焦がれる',
    medium: 'Manga',
    releaseYear: 2017,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Senpai & Kouhai', 'Opposites Attract', 'Slow Burn'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Konatsu Amano moves to a rural seaside town in Ehime. Feeling lonely and anxious, she visits the high school aquarium club and meets the stoic, beautiful Koyuki Honami, who hides her own deep sense of isolation.',
    famousQuote: 'Even an aquarium in the winter snow can be warm when we are together.',
    pairing: 'Konatsu Amano x Koyuki Honami',
    aliases: ['A Tropical Fish Yearns for Snow', 'Nettaigyo wa Yuki ni Kogareru', 'Makoto Hagino', 'Konatsu Koyuki'],
    kitsuType: 'manga',
    searchQuery: 'A Tropical Fish Yearns for Snow'
  },
  {
    id: 'kashimashi',
    title: 'Kashimashi: Girl Meets Girl',
    romaji: 'Kashimashi: Girl Meets Girl',
    nativeTitle: 'かしまし ～ガール・ミーツ・ガール～',
    medium: 'Anime',
    releaseYear: 2006,
    origin: 'Japan',
    setting: 'Sci-Fi/Mecha',
    tropes: ['Childhood Friends', 'Opposites Attract', 'Love Triangle'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Timid boy Hazumu is rejected by Yasuna and flees to Mount Kashimayama, where an alien spaceship crash-lands and kills him. Resurrected by the aliens with an anatomically female body, Hazumu returns to high school as a girl.',
    famousQuote: 'Even though my body changed, my feelings for you never disappeared.',
    pairing: 'Hazumu Osaragi x Yasuna Kamiizumi / Tomari',
    aliases: ['Kashimashi', 'Girl Meets Girl', 'Hazumu', 'Yasuna'],
    kitsuType: 'anime',
    searchQuery: 'Kashimashi: Girl Meets Girl'
  },
  {
    id: 'our-teachers-are-dating',
    title: 'Our Teachers Are Dating!',
    romaji: 'Hayama-sensei to Terano-sensei wa Tsukiatteiru',
    nativeTitle: '早間先生と寺野先生は付き合っている',
    medium: 'Manga',
    releaseYear: 2018,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Roommates', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Hayama-sensei and Terano-sensei are two sweet female teachers working at the same high school. Secretly dating, they spend their lunch breaks and evenings blushing, sharing cuddles, and supporting each other through school days.',
    famousQuote: 'Being teachers by day and girlfriends by night is the greatest joy.',
    pairing: 'Hayama x Terano',
    aliases: ['Our Teachers Are Dating', 'Hayama-sensei', 'Terano-sensei', 'Pikachi Ohi'],
    kitsuType: 'manga',
    searchQuery: 'Hayama-sensei to Terano-sensei wa Tsukiatteiru'
  },
  {
    id: 'tadokoro-san',
    title: 'Tadokoro-san',
    romaji: 'Tadokoro-san',
    nativeTitle: 'タドコロさん',
    medium: 'Manga',
    releaseYear: 2019,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Royalty & Commoner'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Tadokoro is an outcast otaku who secretly draws web manga. One day, Nikaido—the most glamorous, popular girl in school—discovers Tadokoro\'s secret manga account and reveals herself to be her absolute number one super-fan.',
    famousQuote: 'Your manga is brilliant, Tadokoro-san... and you are even cuter!',
    pairing: 'Tadokoro x Nikaido',
    aliases: ['Tadokoro-san', 'Tatsuro', 'Nikaido'],
    kitsuType: 'manga',
    searchQuery: 'Tadokoro-san'
  },
  {
    id: 'school-zone-girls',
    title: 'School Zone Girls',
    romaji: 'School Zone',
    nativeTitle: 'スクールゾーン',
    medium: 'Manga',
    releaseYear: 2018,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Childhood Friends', 'Opposites Attract'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'A chaotic, hilarious comedy chronicling the daily misadventures of delinquent high school girls Yokoyan and Sugiura, whose nonstop bickering and slacker antics mask mutual infatuation.',
    famousQuote: 'We\'re complete hopeless idiots, but at least we\'re hopeless idiots together.',
    pairing: 'Yokoyan x Sugiura',
    aliases: ['School Zone', 'Ningiyau', 'Yokoyan', 'Sugiura'],
    kitsuType: 'manga',
    searchQuery: 'School Zone'
  },
  {
    id: 'vampeerz',
    title: 'Vampeerz',
    romaji: 'Vampeerz: My Peer Vampires',
    nativeTitle: 'ヴァンピアーズ',
    medium: 'Manga',
    releaseYear: 2019,
    origin: 'Japan',
    setting: 'Fantasy/Magic',
    tropes: ['Opposites Attract', 'Age Gap'],
    tone: 'Action/Adventure',
    status: 'Completed',
    synopsis: 'At her grandmother\'s funeral, 14-year-old Ichika meets a mysterious silver-haired foreign girl named Aria. Aria is an ancient vampire seeking an heirloom blade that can finally grant her eternal rest—by Ichika\'s hand.',
    famousQuote: 'The moment our lips touched, I knew you held my life and my death.',
    pairing: 'Ichika x Aria',
    aliases: ['Vampeerz', 'Akili', 'Aria Ichika'],
    kitsuType: 'manga',
    searchQuery: 'Vampeerz'
  },
  {
    id: 'cheerful-amnesia',
    title: 'Cheerful Amnesia',
    romaji: 'Akarui Kioku Soushitsu',
    nativeTitle: '明るい記憶喪失',
    medium: 'Manga',
    releaseYear: 2016,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Roommates', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Mari wakes up in the hospital having lost the last three years of memories—including the fact that she has been happily dating her girlfriend Arisa. Arisa takes her home, and Mari immediately falls in love with her all over again.',
    famousQuote: 'I forgot our entire history, but you are still the cutest girl I\'ve ever seen!',
    pairing: 'Mari x Arisa',
    aliases: ['Cheerful Amnesia', 'Akarui Kioku Soushitsu', 'Kondo Oruko'],
    kitsuType: 'manga',
    searchQuery: 'Akarui Kioku Soushitsu'
  },
  {
    id: 'after-hours',
    title: 'After Hours',
    romaji: 'After Hours',
    nativeTitle: 'アフターアワーズ',
    medium: 'Manga',
    releaseYear: 2015,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Opposites Attract', 'Roommates'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Aimless 24-year-old Emi gets separated from friends at a club and meets Kei, a charismatic and spontaneous female DJ. Kei sweeps Emi into Tokyo\'s vibrant electronic music nightlife, igniting creative sparks and romance.',
    famousQuote: 'The bass drops, the lights flash, and in this crowded club, I only hear your heart.',
    pairing: 'Emi Asano x Kei',
    aliases: ['After Hours', 'Yuhta Nishio', 'Emi Kei'],
    kitsuType: 'manga',
    searchQuery: 'After Hours'
  },
  {
    id: 'even-though-were-adults',
    title: 'Even Though We\'re Adults',
    romaji: 'Otona ni Nattemo',
    nativeTitle: 'おとなになっても',
    medium: 'Manga',
    releaseYear: 2019,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Opposites Attract', 'Love Triangle'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Takako Shimura\'s poignant adult drama: Ayano is an elementary school teacher married to a man, but an unexpected kiss at a dining bar with energetic bartender Akari awakens deep suppressed feelings.',
    famousQuote: 'Growing up doesn\'t mean you ever figure out who your heart belongs to.',
    pairing: 'Ayano x Akari',
    aliases: ['Even Though Were Adults', 'Otona ni Nattemo', 'Takako Shimura'],
    kitsuType: 'manga',
    searchQuery: 'Otona ni Nattemo'
  },
  {
    id: 'hero-san',
    title: 'Hero-san and Former General-san',
    romaji: 'Hero-san to Moto Onna Kanbu-san',
    nativeTitle: 'ヒーローさんと元女幹部さん',
    medium: 'Manga',
    releaseYear: 2018,
    origin: 'Japan',
    setting: 'Fantasy/Magic',
    tropes: ['Enemies to Lovers', 'Roommates', 'Opposites Attract'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'Tokusatsu superheroine Honey Lemon defeats the evil organization Antinoid. Following the collapse of the villain syndicate, former villain general Honey General ends up moving into the superheroine\'s apartment!',
    famousQuote: 'Yesterday we traded lethal kicks—today you\'re cooking breakfast in an apron.',
    pairing: 'Honey Lemon x Former General',
    aliases: ['Hero-san', 'Moto Onna Kanbu-san', 'Sorahiko', 'Hero and General'],
    kitsuType: 'manga',
    searchQuery: 'Hero-san to Moto Onna Kanbu-san'
  },
  {
    id: 'sekai-de-ichiban-oppai',
    title: 'Breasts Are My Favorite Things in the World!',
    romaji: 'Sekai de Ichiban Oppai ga Suki!',
    nativeTitle: '世界で一番おっぱいが好き！',
    medium: 'Manga',
    releaseYear: 2017,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Fake Dating'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'High school girl Chiaki harbors an unabashed obsession with breasts. Her beautiful childhood classmate Hana has an impressive bust, and after a confession of desires, Hana agrees to let Chiaki touch her chest daily.',
    famousQuote: 'I don\'t just love her breasts—I love the girl they\'re attached to!',
    pairing: 'Chiaki x Hana Harumi',
    aliases: ['Breasts Are My Favorite Things in the World', 'Sekai de Ichiban Oppai ga Suki', 'Wakame Konbu'],
    kitsuType: 'manga',
    searchQuery: 'Sekai de Ichiban Oppai ga Suki!'
  },
  {
    id: 'hino-san-no-baka',
    title: 'Hino-san no Baka',
    romaji: 'Hino-san no Baka',
    nativeTitle: '日野さんばか',
    medium: 'Manga',
    releaseYear: 2018,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Childhood Friends'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'Class committee member Koguma constantly tries to stop delinquent slacker Hino from skipping classes behind the school building. In response, Hino plays increasingly intimate and teasing pranks on the flustered straight-A student.',
    famousQuote: 'Hino-san, you idiot! Stop teasing me like that!',
    pairing: 'Hino x Koguma',
    aliases: ['Hino-san no Baka', 'Kinnikutarou', 'Hino Koguma'],
    kitsuType: 'manga',
    searchQuery: 'Hino-san no Baka'
  },
  {
    id: 'sheep-princess',
    title: 'The Sheep Princess in Wolf\'s Clothing',
    romaji: 'Hitsuji Hime no Ookami-san',
    nativeTitle: 'ひつじ姫の狼さん',
    medium: 'Manga',
    releaseYear: 2020,
    origin: 'Japan',
    setting: 'Fantasy/Magic',
    tropes: ['Master & Servant', 'Opposites Attract', 'Royalty & Commoner'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'In a fairy-tale kingdom of demi-humans, Momo the gentle sheep princess selects Aki, a fierce and fearsome female wolf warrior, to be her personal bodyguard. Despite predatory wolf instincts, Aki becomes head-over-heels devoted.',
    famousQuote: 'The wolf was meant to eat the sheep, but instead she gave her heart away.',
    pairing: 'Momo x Aki',
    aliases: ['Hitsuji Hime no Ookami-san', 'Mito', 'Sheep Princess'],
    kitsuType: 'manga',
    searchQuery: 'Hitsuji Hime no Ookami-san'
  },
  {
    id: 'run-away-with-me-girl',
    title: 'Run Away With Me, Girl',
    romaji: 'Kakeochi Girl',
    nativeTitle: 'かけおちガール',
    medium: 'Manga',
    releaseYear: 2020,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Childhood Friends', 'Opposites Attract', 'Love Triangle'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Ten years after high school, Maki runs into her first love Midori at a clinic. Midori is pregnant and trapped in a loveless engagement with an unfaithful fiancé. Maki impulsively takes Midori\'s hand and proposes they elope together.',
    famousQuote: 'Pack your bags and run away with me. I won\'t let anyone break your heart again.',
    pairing: 'Maki x Midori',
    aliases: ['Kakeochi Girl', 'Battan', 'Run Away With Me Girl'],
    kitsuType: 'manga',
    searchQuery: 'Kakeochi Girl'
  },
  {
    id: 'akebi-chan',
    title: 'Akebi\'s Sailor Uniform',
    romaji: 'Akebi-chan no Sailor Fuku',
    nativeTitle: '明日ちゃんのセーラー服',
    medium: 'Anime',
    releaseYear: 2022,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Childhood Friends'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Komichi Akebi wins admission to prestigious Roubai Academy, where she wears a traditional sailor uniform sewn by her mother. With her radiant curiosity, she captivates her classmates, especially the poised pianist Erika Kizaki.',
    famousQuote: 'Erika, will you accompany my dance with your piano?',
    pairing: 'Komichi Akebi x Erika Kizaki',
    aliases: ['Akebi-chan no Sailor Fuku', 'Akebi', 'Erika Kizaki', 'CloverWorks'],
    kitsuType: 'anime',
    searchQuery: 'Akebi-chan no Sailor Fuku'
  },
  {
    id: 'candy-boy',
    title: 'Candy Boy',
    romaji: 'Candy Boy',
    nativeTitle: 'キャンディ☆ボーイ',
    medium: 'Anime',
    releaseYear: 2008,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Roommates', 'Childhood Friends'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Twin sisters Kanade and Yukino Sakurai share a room at an all-girls student dormitory in Tokyo. Their exceptionally sweet, affectionate daily intimacy is gently complicated by an enthusiastic junior classmate, Sakuya.',
    famousQuote: 'No matter what happens, Yukino and I will always share one umbrella.',
    pairing: 'Kanade Sakurai x Yukino Sakurai',
    aliases: ['Candy Boy', 'Kanade Yukino', 'AIC'],
    kitsuType: 'anime',
    searchQuery: 'Candy Boy'
  },
  {
    id: 'kuttsukiboshi',
    title: 'Kuttsukiboshi',
    romaji: 'Kuttsukiboshi',
    nativeTitle: 'くっつきぼし',
    medium: 'Anime',
    releaseYear: 2010,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Love Triangle'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Kiiko Kawakami has psychic telekinetic powers. During empty summer vacation classrooms, she meets mysterious transfer student Aaya Saito, embarking on an emotionally charged and mystical romantic bond.',
    famousQuote: 'With these psychic hands, the only thing I want to hold is you.',
    pairing: 'Kiiko Kawakami x Aaya Saito',
    aliases: ['Kuttsukiboshi', 'Primastea', 'Kiiko Aaya'],
    kitsuType: 'anime',
    searchQuery: 'Kuttsukiboshi'
  },
  {
    id: 'sono-hanabira',
    title: 'A Kiss for the Petals',
    romaji: 'Sono Hanabira ni Kuchizuke wo',
    nativeTitle: 'その花びらにくちづけを',
    medium: 'Anime',
    releaseYear: 2010,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Senpai & Kouhai', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'At the prestigious St. Michael\'s Girls Academy, elegant student council president Nanami and cheerful kouhai Yuuna navigate their secret romantic relationship behind campus doors.',
    famousQuote: 'A single petal falls, sealed with our sweetest kiss.',
    pairing: 'Nanami Oda x Yuuna Matsubara',
    aliases: ['Sono Hanabira', 'A Kiss for the Petals', 'Nanami Yuuna', 'Fuguriya'],
    kitsuType: 'anime',
    searchQuery: 'Sono Hanabira ni Kuchizuke wo'
  },
  {
    id: 'qualia-the-purple',
    title: 'Qualia the Purple',
    romaji: 'Murasakiiro no Qualia',
    nativeTitle: '紫色のクオリア',
    medium: 'Light Novel',
    releaseYear: 2009,
    origin: 'Japan',
    setting: 'Sci-Fi/Mecha',
    tropes: ['Childhood Friends', 'Opposites Attract'],
    tone: 'Dark/Psychological',
    status: 'Completed',
    synopsis: 'Mariii Marii sees all humans as mechanical robots, but possesses mysterious superhuman abilities. When Mariii is murdered by a shadowy scientific cabal, her friend Manabu Gaku shifts across countless parallel quantum universes for centuries to save her.',
    famousQuote: 'Even if I have to dismantle the universe itself, I will bring you back.',
    pairing: 'Manabu Gaku x Mariii Marii',
    aliases: ['Qualia the Purple', 'Murasakiiro no Qualia', 'Hisamitsu Ueo', 'Manabu Mariii'],
    kitsuType: 'manga',
    searchQuery: 'Murasakiiro no Qualia'
  },
  {
    id: 'vtuber-legend',
    title: 'VTuber Legend',
    romaji: 'VTuber Nanda ga Haishin Kiri Wasuretara Densetsu ni Natteta',
    nativeTitle: 'VTuberなんだが配信切り忘れたら伝説になってた',
    medium: 'Anime',
    releaseYear: 2024,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Opposites Attract', 'Roommates'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'Awayuki Kokorone is a refined VTuber until she forgets to end her stream and ends up drunkenly chugging beer and rambling yuri fantasies live to hundreds of thousands. Soon, real sparks fly with idol VTuber Mashiro.',
    famousQuote: 'I forgot to turn off the stream, but my love for cute girls was 100% real!',
    pairing: 'Awayuki Kokorone x Mashiro Irodori',
    aliases: ['VTuber Legend', 'Awayuki', 'Live-On'],
    kitsuType: 'anime',
    searchQuery: 'VTuber Legend'
  },
  {
    id: 'train-to-the-end',
    title: 'Train to the End of the World',
    romaji: 'Shuumatsu Train Doko e Iku?',
    nativeTitle: '終末トレインどこへいく？',
    medium: 'Anime',
    releaseYear: 2024,
    origin: 'Japan',
    setting: 'Sci-Fi/Mecha',
    tropes: ['Childhood Friends', 'Opposites Attract'],
    tone: 'Action/Adventure',
    status: 'Completed',
    synopsis: 'Following an experimental 7G cellular launch that mutates the world, high schooler Shizuru Chikura commandeers an abandoned Seibu train with friends to travel down apocalyptic railroad tracks to find her lost best friend Yoka.',
    famousQuote: 'We will ride this train to the very edge of the earth just to see you again.',
    pairing: 'Shizuru Chikura x Yoka Nakakuni',
    aliases: ['Train to the End of the World', 'Shuumatsu Train Doko e Iku', 'Tsutomu Mizushima'],
    kitsuType: 'anime',
    searchQuery: 'Shuumatsu Train Doko e Iku?'
  },
  {
    id: 'inugami-nekoyama',
    title: 'Inugami-san to Nekoyama-san',
    romaji: 'Inugami-san to Nekoyama-san',
    nativeTitle: '犬神さんと猫山さん',
    medium: 'Anime',
    releaseYear: 2014,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'Yachiyo Inugami is a dog-like girl who adores cats, while Suzu Nekoyama is a cat-like girl who loves dogs. When their mutual friend Aki introduces them, immediate sparks and comedy ignite between canine and feline personalities.',
    famousQuote: 'She\'s like a cat, and I\'m like a puppy—we\'re destined to tumble together!',
    pairing: 'Yachiyo Inugami x Suzu Nekoyama',
    aliases: ['Inugami-san to Nekoyama-san', 'Inugami Nekoyama', 'Kuzushiro'],
    kitsuType: 'anime',
    searchQuery: 'Inugami-san to Nekoyama-san'
  },
  {
    id: 'octave',
    title: 'Octave',
    romaji: 'Octave',
    nativeTitle: 'オクターヴ',
    medium: 'Manga',
    releaseYear: 2008,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Opposites Attract', 'Roommates'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Yukino is a 18-year-old former teen idol whose pop group disbanded in failure. Disowned by her family, she attends a manager\'s wedding and meets Setsuko, a cynical audio engineer. A mature, raw romance unfolds in Tokyo.',
    famousQuote: 'We are both broken chords that found a way to harmonize.',
    pairing: 'Yukino Miyagawa x Setsuko Iwai',
    aliases: ['Octave', 'Haru Akiyama', 'Yukino Setsuko'],
    kitsuType: 'manga',
    searchQuery: 'Octave'
  },
  {
    id: 'prism-yuri',
    title: 'Prism',
    romaji: 'Prism',
    nativeTitle: 'プリズム',
    medium: 'Manga',
    releaseYear: 2010,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Slow Burn'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Megumi enters high school hoping for romance and encounters Hikaru, a tall, handsome girl who inadvertently steals her heart. A beautifully drawn, tender high school romance filled with gentle discoveries.',
    famousQuote: 'Like white light through a prism, being with you shows me every color.',
    pairing: 'Megumi x Hikaru',
    aliases: ['Prism Yuri', 'Higashiyama', 'Megumi Hikaru'],
    kitsuType: 'manga',
    searchQuery: 'Prism'
  },
  {
    id: 'gunjou',
    title: 'Gunjou (Ride or Die)',
    romaji: 'Gunjou',
    nativeTitle: '羣青',
    medium: 'Manga',
    releaseYear: 2007,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Enemies to Lovers', 'Childhood Friends'],
    tone: 'Dark/Psychological',
    status: 'Completed',
    synopsis: 'Ching Nakamura\'s gripping noir thriller: A lesbian doctor murders the abusive husband of her former classmate Nanae at her desperate request. Bound by blood and guilt, the two women flee on an apocalyptic road trip across Japan.',
    famousQuote: 'I murdered for you. Now there is nowhere left to run except into each other.',
    pairing: 'Rei Nagasawa x Nanae Shinoda',
    aliases: ['Gunjou', 'Ride or Die', 'Ching Nakamura'],
    kitsuType: 'manga',
    searchQuery: 'Gunjou'
  },
  {
    id: 'blue-drop',
    title: 'Blue Drop: Tenshi-tachi no Gikyoku',
    romaji: 'Blue Drop: Tenshi-tachi no Gikyoku',
    nativeTitle: 'BLUE DROP ～天使達の戯曲～',
    medium: 'Anime',
    releaseYear: 2007,
    origin: 'Japan',
    setting: 'Sci-Fi/Mecha',
    tropes: ['Enemies to Lovers', 'Opposites Attract'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Mari lost all childhood memories when her entire island was wiped out in a mysterious catastrophe. Sent to an elite academy, she meets Hagino, an alien commander torn between duty to her invading race and her love for Mari.',
    famousQuote: 'My spaceship came to conquer your world, but your eyes conquered my soul.',
    pairing: 'Mari Wakatake x Hagino Senkouji',
    aliases: ['Blue Drop', 'Tenshi-tachi no Gikyoku', 'Mari Hagino'],
    kitsuType: 'anime',
    searchQuery: 'Blue Drop: Tenshi-tachi no Gikyoku'
  },
  {
    id: 'mnemosyne',
    title: 'Rin: Daughters of Mnemosyne',
    romaji: 'Mnemosyne: Mnemosyne no Musume-tachi',
    nativeTitle: 'Mnemosyne -ムネモシュネの娘たち-',
    medium: 'Anime',
    releaseYear: 2008,
    origin: 'Japan',
    setting: 'Sci-Fi/Mecha',
    tropes: ['Roommates', 'Age Gap'],
    tone: 'Dark/Psychological',
    status: 'Completed',
    synopsis: 'Rin Asogi is an immortal private investigator in Shinjuku who has tasted death countless times. Alongside her hacker assistant Mimi, Rin investigates sinister biotechnical horrors across six decades of modern and futuristic Tokyo.',
    famousQuote: 'Spanning sixty years and a hundred deaths, Mimi and I endure.',
    pairing: 'Rin Asogi x Mimi',
    aliases: ['Mnemosyne', 'Daughters of Mnemosyne', 'Rin Asogi', 'Xebec'],
    kitsuType: 'anime',
    searchQuery: 'Mnemosyne: Mnemosyne no Musume-tachi'
  },
  {
    id: 'noir',
    title: 'Noir',
    romaji: 'Noir',
    nativeTitle: 'ノワール',
    medium: 'Anime',
    releaseYear: 2001,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Master & Servant', 'Opposites Attract'],
    tone: 'Action/Adventure',
    status: 'Completed',
    synopsis: 'Bee Train\'s classic girls-with-guns thriller: Corsican assassin Mireille Bouquet teams up with amnesiac Japanese assassin prodigy Kirika Yuumura under the ancient codename "Noir" to uncover their intertwined bloodstained past.',
    famousQuote: 'Noir... an ancient name for fate, spoken only by two maidens holding guns.',
    pairing: 'Mireille Bouquet x Kirika Yuumura',
    aliases: ['Noir', 'Bee Train', 'Mireille Kirika'],
    kitsuType: 'anime',
    searchQuery: 'Noir'
  },
  {
    id: 'el-cazador',
    title: 'El Cazador de la Bruja',
    romaji: 'El Cazador de la Bruja',
    nativeTitle: 'エル・カザド',
    medium: 'Anime',
    releaseYear: 2007,
    origin: 'Japan',
    setting: 'Fantasy/Magic',
    tropes: ['Opposites Attract', 'Roommates'],
    tone: 'Action/Adventure',
    status: 'Completed',
    synopsis: 'Bounty hunter Nadie tracks down Ellis, a genetically engineered "witch" wanted for murder. Instead of turning her in for the reward, Nadie becomes Ellis\'s protector on a dusty road trip south toward the legendary holy land of Wiñay Marka.',
    famousQuote: 'I was hired to hunt you, but I\'d rather spend my bullets protecting you.',
    pairing: 'Nadie x Ellis',
    aliases: ['El Cazador de la Bruja', 'Nadie Ellis', 'Bee Train'],
    kitsuType: 'anime',
    searchQuery: 'El Cazador de la Bruja'
  },
  {
    id: 'madlax',
    title: 'Madlax',
    romaji: 'Madlax',
    nativeTitle: 'マドラックス',
    medium: 'Anime',
    releaseYear: 2004,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Opposites Attract'],
    tone: 'Action/Adventure',
    status: 'Completed',
    synopsis: 'In war-torn Gazth-Sonika, elite mercenary Madlax can dodge bullets with uncanny grace. Meanwhile in peaceful Nafrece, wealthy aristocrat Margaret Burton seeks memories of a tragedy twelve years ago. Their souls are tied by a holy book.',
    famousQuote: 'Across two halves of the world, our lives are woven by the same melody.',
    pairing: 'Madlax x Margaret Burton',
    aliases: ['Madlax', 'Bee Train', 'Margaret'],
    kitsuType: 'anime',
    searchQuery: 'Madlax'
  },
  {
    id: 'kakegurui',
    title: 'Kakegurui',
    romaji: 'Kakegurui',
    nativeTitle: '賭ケグルイ',
    medium: 'Anime',
    releaseYear: 2017,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Enemies to Lovers', 'Opposites Attract'],
    tone: 'Dark/Psychological',
    status: 'Completed',
    synopsis: 'At Hyakkaou Private Academy, social hierarchy is determined solely by high-stakes gambling. Compulsive gambler Yumeko Jabami turns the academy upside down, igniting intense rivalry and magnetic tension with Mary Saotome.',
    famousQuote: 'Let us gamble until our minds shatter completely!',
    pairing: 'Mary Saotome x Yumeko Jabami / Ririka Momobami',
    aliases: ['Kakegurui', 'Mary Saotome', 'Yumeko Jabami', 'Meariri'],
    kitsuType: 'anime',
    searchQuery: 'Kakegurui'
  },
  {
    id: 'cross-ange',
    title: 'Cross Ange: Rondo of Angel and Dragon',
    romaji: 'Cross Ange: Tenshi to Ryuu no Rondo',
    nativeTitle: 'クロスアンジュ 天使と竜の輪舞',
    medium: 'Anime',
    releaseYear: 2014,
    origin: 'Japan',
    setting: 'Sci-Fi/Mecha',
    tropes: ['Enemies to Lovers', 'Royalty & Commoner'],
    tone: 'Action/Adventure',
    status: 'Completed',
    synopsis: 'Princess Angelise is stripped of royalty and exiled to the frontline base Arzenal when she is revealed to be a "Norma" who cannot use Mana. Battling invading DRAGONs in mecha, she wins the fiery devotion of rebel pilot Hilda.',
    famousQuote: 'I will survive, spit on this rotten world, and take everything I want!',
    pairing: 'Angelise Ikaruga Misurugi x Hilda',
    aliases: ['Cross Ange', 'Ange Hilda', 'Sunrise Mecha'],
    kitsuType: 'anime',
    searchQuery: 'Cross Ange: Tenshi to Ryuu no Rondo'
  },
  {
    id: 'valkyrie-drive',
    title: 'Valkyrie Drive: Mermaid',
    romaji: 'Valkyrie Drive: Mermaid',
    nativeTitle: 'ヴァルキリードライヴ マーメイド',
    medium: 'Anime',
    releaseYear: 2015,
    origin: 'Japan',
    setting: 'Sci-Fi/Mecha',
    tropes: ['Master & Servant', 'Opposites Attract'],
    tone: 'Action/Adventure',
    status: 'Completed',
    synopsis: 'On artificial prison islands, girls infected with the A-Virus can transform into lethal weapons (Extars) through sexual arousal provided by Liberators. Timid Mamori transforms into a sacred sword wielded by fierce fighter Mirei.',
    famousQuote: 'Kiss me, Mamori... let me draw your blade!',
    pairing: 'Mamori Tokonome x Mirei Shikishima',
    aliases: ['Valkyrie Drive Mermaid', 'Mamori Mirei', 'Arms'],
    kitsuType: 'anime',
    searchQuery: 'Valkyrie Drive: Mermaid'
  },
  {
    id: 'assault-lily',
    title: 'Assault Lily: Bouquet',
    romaji: 'Assault Lily: Bouquet',
    nativeTitle: 'アサルトリリィ BOUQUET',
    medium: 'Anime',
    releaseYear: 2020,
    origin: 'Japan',
    setting: 'Fantasy/Magic',
    tropes: ['Senpai & Kouhai', 'Master & Servant'],
    tone: 'Action/Adventure',
    status: 'Completed',
    synopsis: 'Teenage warrior maidens known as "Lilies" wield transforming CHARM weapons to battle monstrous Huge. Optimistic rookie Riri enrolls at elite Yurigaoka Academy to become the Schutzengel partner of stoic ace Yuyu Shirai.',
    famousQuote: 'I became a Lily because I wanted to fight by your side, Yuyu-sama!',
    pairing: 'Riri Hitotsuyanagi x Yuyu Shirai',
    aliases: ['Assault Lily Bouquet', 'Shaft', 'Riri Yuyu'],
    kitsuType: 'anime',
    searchQuery: 'Assault Lily: Bouquet'
  },
  {
    id: 'granbelm',
    title: 'Granbelm',
    romaji: 'Granbelm',
    nativeTitle: 'グランベルム',
    medium: 'Anime',
    releaseYear: 2019,
    origin: 'Japan',
    setting: 'Sci-Fi/Mecha',
    tropes: ['Opposites Attract', 'Master & Servant'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Under every full moon, high schoolers pilot giant magical mecha Armanox to battle for the mantle of the world\'s single Magiaconatus sorceress. Ordinary girl Mangetsu meets stoic doll-like rival Shingetsu Ernesta Fukami.',
    famousQuote: 'Even if magic disappears from this world, our memories never will.',
    pairing: 'Mangetsu Kohinata x Shingetsu Ernesta Fukami',
    aliases: ['Granbelm', 'Nexus', 'Mangetsu Shingetsu'],
    kitsuType: 'anime',
    searchQuery: 'Granbelm'
  },
  {
    id: 'slow-loop',
    title: 'Slow Loop',
    romaji: 'Slow Loop',
    nativeTitle: 'スローループ',
    medium: 'Anime',
    releaseYear: 2022,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Roommates', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Hiyori loves fly-fishing, a pastime taught by her deceased father. When her mother remarries, she discovers her new stepsister is cheerful Koharu, and the two girls bond deeply over fly-fishing and homemade meals.',
    famousQuote: 'Casting our lines side-by-side makes the whole world feel peaceful.',
    pairing: 'Hiyori Minagi x Koharu Minagi',
    aliases: ['Slow Loop', 'Connect', 'Fly Fishing Yuri'],
    kitsuType: 'anime',
    searchQuery: 'Slow Loop'
  },
  {
    id: 'asteroid-in-love',
    title: 'Asteroid in Love',
    romaji: 'Koisuru Asteroid',
    nativeTitle: '恋する小惑星',
    medium: 'Anime',
    releaseYear: 2020,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Childhood Friends', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'As a child, Mira met a boy named Ao at a campsite and promised to discover an asteroid together. Entering high school astronomy club, she discovers "Ao" is actually a girl, and their childhood promise burns brighter than ever.',
    famousQuote: 'We promised under the summer night sky: we will name an asteroid together!',
    pairing: 'Mira Konohata x Ao Manaka',
    aliases: ['Asteroid in Love', 'Koisuru Asteroid', 'Doga Kobo', 'Mira Ao'],
    kitsuType: 'anime',
    searchQuery: 'Koisuru Asteroid'
  },
  {
    id: 'kiniro-mosaic',
    title: 'Kin-iro Mosaic',
    romaji: 'Kin-iro Mosaic',
    nativeTitle: 'きんいろモザイク',
    medium: 'Anime',
    releaseYear: 2013,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Childhood Friends'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Shinobu Omiya homestayed in England with Alice Cartelet. Years later, blonde Alice moves to Japan to live with Shinobu, alongside boisterous half-British Karen Kujo and mutual childhood friends Aya and Yoko.',
    famousQuote: 'Shino! I crossed the sea from England just to be with you!',
    pairing: 'Shinobu x Alice / Aya x Yoko',
    aliases: ['Kin-iro Mosaic', 'Kinmoza', 'Alice Cartelet', 'Aya Yoko'],
    kitsuType: 'anime',
    searchQuery: 'Kin-iro Mosaic'
  },
  {
    id: 'gochuumon-wa-usagi',
    title: 'Is the Order a Rabbit?',
    romaji: 'Gochuumon wa Usagi Desu ka?',
    nativeTitle: 'ご注文はうさぎですか？',
    medium: 'Anime',
    releaseYear: 2014,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Roommates', 'Senpai & Kouhai'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Cocoa moves to a European-style storybook town to board at the Rabbit House cafe. She treats younger barista Chino like a beloved little sister, while cafe coworker Rize and green tea maiden Sharo share adorable romantic chemistry.',
    famousQuote: 'My heart is all hop-stepping! Leave everything to your big sister Cocoa!',
    pairing: 'Cocoa x Chino / Rize x Sharo',
    aliases: ['Gochuumon wa Usagi Desu ka', 'Gochiusa', 'Is the Order a Rabbit', 'Rize Sharo'],
    kitsuType: 'anime',
    searchQuery: 'Gochuumon wa Usagi Desu ka?'
  },
  {
    id: 'non-non-biyori',
    title: 'Non Non Biyori',
    romaji: 'Non Non Biyori',
    nativeTitle: 'のんのんびより',
    medium: 'Anime',
    releaseYear: 2013,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Senpai & Kouhai', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Hotaru Ichijou transfers from Tokyo to a tiny countryside school with only five students. Despite being an elementary fifth-grader, she towers over petite middle-schooler Komari Koshigaya, harboring a secret room packed with handmade Komari plushies.',
    famousQuote: 'Koma-chan is the most adorable person in the entire world!',
    pairing: 'Hotaru Ichijou x Komari Koshigaya',
    aliases: ['Non Non Biyori', 'Nyanpasu', 'Hotaru Komari', 'Koma-chan'],
    kitsuType: 'anime',
    searchQuery: 'Non Non Biyori'
  },
  {
    id: 'comic-girls',
    title: 'Comic Girls',
    romaji: 'Comic Girls',
    nativeTitle: 'こみっくがーるず',
    medium: 'Anime',
    releaseYear: 2018,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Roommates', 'Opposites Attract'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'Struggling 4-koma manga artist Kaoruko Moeta (Chaos) moves into an all-girls manga creator dormitory. Living with shoujo artist Koyume, boy\'s love artist Ruki, and shonen artist Tsubasa, they encourage each other through deadlines.',
    famousQuote: 'Ababababa! My manuscripts are in trouble, but my roommates give me courage!',
    pairing: 'Kaoruko x Koyume / Ruki x Tsubasa',
    aliases: ['Comic Girls', 'Chaos-chan', 'Nexus'],
    kitsuType: 'anime',
    searchQuery: 'Comic Girls'
  },
  {
    id: 'new-game',
    title: 'New Game!',
    romaji: 'New Game!',
    nativeTitle: 'NEW GAME!',
    medium: 'Anime',
    releaseYear: 2016,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Roommates', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Aoba Suzukaze joins video game studio Eagle Jump right after high school. Working on Fairies Story 3 under character designer Kou Yagami, she witnesses the longtime domestic intimacy between senior designers Kou and Rin Toyama.',
    famousQuote: 'Rin has always been the one looking out for me, in the office and at home.',
    pairing: 'Kou Yagami x Rin Toyama',
    aliases: ['New Game', 'Eagle Jump', 'Kou Rin', 'Aoba'],
    kitsuType: 'anime',
    searchQuery: 'New Game!'
  },
  {
    id: 'fluttering-feelings',
    title: 'Fluttering Feelings',
    romaji: 'Fluttering Feelings',
    nativeTitle: '설레는 기분',
    medium: 'Manhwa',
    releaseYear: 2014,
    origin: 'South Korea',
    setting: 'College/University',
    tropes: ['Opposites Attract', 'Slow Burn'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Ssamba\'s beloved Korean manhwa classic: Business major Kim No-rae is sensible and reserved. When she meets popular, stunning classmate Baek Seol-a, an unforgettable slow-burn romance blossoms between campus lectures and rainy evenings.',
    famousQuote: 'Whenever I see your face, my heart flutters with feelings I never understood.',
    pairing: 'Kim No-rae x Baek Seol-a',
    aliases: ['Fluttering Feelings', 'Ssamba', 'No-rae', 'Seol-a'],
    kitsuType: 'manga',
    searchQuery: 'Fluttering Feelings'
  },
  {
    id: 'lily-love',
    title: 'Lily Love',
    romaji: 'Lily Love',
    nativeTitle: 'Lily Love',
    medium: 'Webtoon',
    releaseYear: 2015,
    origin: 'Other',
    setting: 'College/University',
    tropes: ['Opposites Attract', 'Roommates'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Ratana Satis\'s smash-hit Thai GL webtoon: Innocent university student Donut moves into a new apartment complex and encounters Mew, an alluring senior architecture student next door who opens her heart to love.',
    famousQuote: 'Love blooms softly, like a pure white lily in summer.',
    pairing: 'Donut x Mew',
    aliases: ['Lily Love', 'Ratana Satis', 'Donut Mew'],
    kitsuType: 'manga',
    searchQuery: 'Lily Love Ratana Satis'
  },
  {
    id: 'moonlight-garden',
    title: 'Moonlight Garden',
    romaji: 'Moonlight Garden',
    nativeTitle: '달빛 화원',
    medium: 'Manhwa',
    releaseYear: 2017,
    origin: 'South Korea',
    setting: 'Historical/Period',
    tropes: ['Master & Servant', 'Enemies to Lovers', 'Royalty & Commoner'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Set in a historical pleasure brothel of flower maidens with aphrodisiac scents, Dohwa seeks a rare potion to escape her courtesan fate. She becomes ensnared in a passionate triangle with young mistress Lady Hyewon and guard Yushin.',
    famousQuote: 'In this flower garden of moonlight and desire, you are my only freedom.',
    pairing: 'Dohwa x Hyewon / Yushin',
    aliases: ['Moonlight Garden', 'Dohwa', 'Hyewon', 'Lezhin GL'],
    kitsuType: 'manga',
    searchQuery: 'Moonlight Garden'
  },
  {
    id: 'ring-my-bell',
    title: 'Ring My Bell!',
    romaji: 'Ring My Bell!',
    nativeTitle: '딩동설',
    medium: 'Manhwa',
    releaseYear: 2019,
    origin: 'South Korea',
    setting: 'Workplace',
    tropes: ['Enemies to Lovers', 'Roommates', 'Opposites Attract'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'Webtoon artist Sohn Yeon-woo gets assigned to write a romance webtoon right after being dumped. Her uptight new neighbor Mai complains about thin apartment walls, but soon agrees to help Yeon-woo study romance.',
    famousQuote: 'Our doorbells kept ringing, until you finally walked into my life.',
    pairing: 'Sohn Yeon-woo x Mai',
    aliases: ['Ring My Bell', 'Yeonji', 'Yeon-woo Mai'],
    kitsuType: 'manga',
    searchQuery: 'Ring My Bell'
  },
  {
    id: 'sora-haena',
    title: 'Sora & Haena',
    romaji: 'Sora & Haena',
    nativeTitle: '소라와 해나',
    medium: 'Manhwa',
    releaseYear: 2019,
    origin: 'South Korea',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Fake Dating'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Haena is a stylish gyaru girl who wants to look cool but has zero dating experience. Timid model student Sora agrees to give her private dating tutoring in exchange for help making friends.',
    famousQuote: 'Tutoring you about dating was supposed to be easy... until I fell for you.',
    pairing: 'Sora x Haena',
    aliases: ['Sora & Haena', 'Sora Haena', 'Aji'],
    kitsuType: 'manga',
    searchQuery: 'Sora & Haena'
  },
  {
    id: 'opium-gl',
    title: 'Opium',
    romaji: 'Opium',
    nativeTitle: '오피움',
    medium: 'Manhwa',
    releaseYear: 2019,
    origin: 'South Korea',
    setting: 'Historical/Period',
    tropes: ['Enemies to Lovers', 'Royalty & Commoner'],
    tone: 'Dark/Psychological',
    status: 'Completed',
    synopsis: 'In Japanese-occupied 1940s Gyeongseong, female physician Mary treats high-society patients. When she is called to examine the mysterious, aristocratic Lady Marianne, an intoxicating and dangerous conspiracy unfolds.',
    famousQuote: 'Your touch is an addictive poison I have no desire to cure.',
    pairing: 'Doctor Mary x Lady Marianne',
    aliases: ['Opium', 'Aji', 'Mary Marianne'],
    kitsuType: 'manga',
    searchQuery: 'Opium Aji'
  },
  {
    id: 'nevermore-webtoon',
    title: 'Nevermore',
    romaji: 'Nevermore',
    nativeTitle: 'Nevermore',
    medium: 'Webtoon',
    releaseYear: 2022,
    origin: 'Other',
    setting: 'Fantasy/Magic',
    tropes: ['Enemies to Lovers', 'Roommates'],
    tone: 'Dark/Psychological',
    status: 'Ongoing',
    synopsis: 'Kit & Trace\'s hit gothic supernatural Webtoon inspired by Edgar Allan Poe: In the afterlife Academy of Nevermore, deceased souls Annabel Lee and Lenore must compete in gruesome trials to reclaim their forgotten earthly memories.',
    famousQuote: 'We loved with a love that was more than love.',
    pairing: 'Annabel Lee x Lenore',
    aliases: ['Nevermore', 'Kit & Trace', 'Annabel Lee', 'Lenore'],
    kitsuType: 'manga',
    searchQuery: 'Nevermore'
  },
  {
    id: 'always-human',
    title: 'Always Human',
    romaji: 'Always Human',
    nativeTitle: 'Always Human',
    medium: 'Webtoon',
    releaseYear: 2015,
    origin: 'Other',
    setting: 'Sci-Fi/Mecha',
    tropes: ['Opposites Attract', 'Slow Burn'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'In a near future where nanotech body modifications allow everyone to change hair, eye color, and biology instantly, Sunati notices Austen, a girl without mods due to an autoimmune disorder. A tender, luminous romance begins.',
    famousQuote: 'No matter what mods you wear, you are always beautifully human to me.',
    pairing: 'Sunati x Austen',
    aliases: ['Always Human', 'Ari North', 'WalkingNorth'],
    kitsuType: 'manga',
    searchQuery: 'Always Human'
  },
  {
    id: 'soulmate-gl',
    title: 'Soulmate',
    romaji: 'Soulmate',
    nativeTitle: '双生灵探 / 灵魂伴侣',
    medium: 'Manhua',
    releaseYear: 2020,
    origin: 'China',
    setting: 'High School',
    tropes: ['Childhood Friends', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Ke Ran Bing\'s celebrated emotional time-travel romance: 27-year-old Qi Yan awakens ten years in the past as a high school senior. Determined to prevent her dying lover Yuan Zi\'s tragic illness, she cherishes every single second.',
    famousQuote: 'If time gives me a second chance, I will hold you tight and never let you slip away.',
    pairing: 'Qi Yan x Yuan Zi',
    aliases: ['Soulmate', 'Ke Ran Bing', 'Qi Yan Yuan Zi'],
    kitsuType: 'manga',
    searchQuery: 'Soulmate Ke Ran Bing'
  },
  {
    id: 'baili-jin',
    title: 'Baili Jin Among Mortals',
    romaji: 'Baili Jin Among Mortals',
    nativeTitle: '百里金在人间',
    medium: 'Manhua',
    releaseYear: 2020,
    origin: 'China',
    setting: 'Fantasy/Magic',
    tropes: ['Opposites Attract', 'Roommates'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Baili Jin, a fairy from the heavenly realm, descends to the mortal world to experience modern life. She moves in with ordinary mortal woman Tong Sisi, learning about city life, bubble tea, and romantic feelings.',
    famousQuote: 'The mortal world has many wonders, but none shine brighter than you.',
    pairing: 'Baili Jin x Tong Sisi',
    aliases: ['Baili Jin Among Mortals', 'Baili Jin', 'Tong Sisi'],
    kitsuType: 'manga',
    searchQuery: 'Baili Jin Among Mortals'
  },
  {
    id: 'straight-girl-trap',
    title: 'Straight Girl Trap',
    romaji: 'Straight Girl Trap',
    nativeTitle: '直女陷阱',
    medium: 'Manhua',
    releaseYear: 2021,
    origin: 'China',
    setting: 'Workplace',
    tropes: ['Enemies to Lovers', 'Opposites Attract'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'Chen Ling is convinced her capable, charismatic female corporate manager Xiao Nan is an unattainable "straight girl." But as Xiao Nan gives her flirtatious signals and private favors, the line between straight and smitten dissolves.',
    famousQuote: 'Are you really straight, or is this the sweetest trap I\'ve ever stepped into?',
    pairing: 'Chen Ling x Xiao Nan',
    aliases: ['Straight Girl Trap', 'Chen Ling', 'Xiao Nan'],
    kitsuType: 'manga',
    searchQuery: 'Straight Girl Trap'
  },
  {
    id: 'lily-yy',
    title: 'Lily',
    romaji: 'Lily',
    nativeTitle: 'Lily',
    medium: 'Manhua',
    releaseYear: 2016,
    origin: 'China',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Slow Burn'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Yy\'s legendary marathon manhua following energetic athlete Fan Yilun and quiet model student Ruoxi from their first high school meeting through years of emotional growth, friendship, and unspoken love.',
    famousQuote: 'Year after year, my gaze always returns to where you are standing.',
    pairing: 'Fan Yilun x Ruoxi',
    aliases: ['Lily Yy', 'Fan Yilun', 'Ruoxi'],
    kitsuType: 'manga',
    searchQuery: 'Lily'
  },
  {
    id: 'relationship-guidelines',
    title: 'Relationship Guidelines',
    romaji: 'Kanojo to Kare no Kankei',
    nativeTitle: '그녀의 심청 / 연애 가이드라인',
    medium: 'Manhwa',
    releaseYear: 2020,
    origin: 'South Korea',
    setting: 'High School',
    tropes: ['Childhood Friends', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Jiwon and Jisoo have been inseparable best friends since childhood. When Jisoo proposes they establish "guidelines" for their relationship, both girls struggle to suppress feelings that clearly cross into romance.',
    famousQuote: 'Best friends don\'t kiss like this... so what are we now?',
    pairing: 'Jiwon x Jisoo',
    aliases: ['Relationship Guidelines', 'Jiwon Jisoo'],
    kitsuType: 'manga',
    searchQuery: 'Relationship Guidelines'
  },
  {
    id: 'white-angels-have-no-wings',
    title: 'White Angels Have No Wings',
    romaji: 'White Angels Have No Wings',
    nativeTitle: '하얀 천사는 날개가 없다',
    medium: 'Manhwa',
    releaseYear: 2016,
    origin: 'South Korea',
    setting: 'High School',
    tropes: ['Enemies to Lovers', 'Opposites Attract'],
    tone: 'Dark/Psychological',
    status: 'Completed',
    synopsis: 'At an austere Christian girls high school, meek victim Ayeon is tormented by bullies until ruthless transfer student Minseo arrives. A toxic, hypnotic psychological relationship forms between savior and victim.',
    famousQuote: 'In this cruel purgatory, even the angels carry wicked thorns.',
    pairing: 'Ayeon x Minseo',
    aliases: ['White Angels Have No Wings', 'White Angels Get No Rest', 'Gado'],
    kitsuType: 'manga',
    searchQuery: 'White Angels Have No Wings'
  },
  {
    id: 'the-third-party',
    title: 'The Third Party',
    romaji: 'The Third Party',
    nativeTitle: '제3자',
    medium: 'Manhwa',
    releaseYear: 2017,
    origin: 'South Korea',
    setting: 'Workplace',
    tropes: ['Opposites Attract', 'Love Triangle'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Song Jeong-eun enters an arranged political marriage arranged by her chaebol family. At the broadcast station, she encounters fierce, passionate TV producer PD Kang, leading to an explosive affair.',
    famousQuote: 'My marriage was an illusion—you are the only truth I want.',
    pairing: 'Song Jeong-eun x PD Kang',
    aliases: ['The Third Party', 'Enjelicious', 'PD Kang'],
    kitsuType: 'manga',
    searchQuery: 'The Third Party'
  },
  {
    id: 'serenade-manhwa',
    title: 'Serenade',
    romaji: 'Serenade',
    nativeTitle: '세레나데',
    medium: 'Manhwa',
    releaseYear: 2019,
    origin: 'South Korea',
    setting: 'College/University',
    tropes: ['Opposites Attract', 'Slow Burn'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'At a prestigious university music conservatory, Hayeon is captivated by brilliant cello prodigy Jin-ah. Amidst the demanding pressure of classical recitals, their music mirrors intense, unspoken romantic longing.',
    famousQuote: 'Every bow drawn across the strings plays a serenade only meant for you.',
    pairing: 'Hayeon x Jin-ah',
    aliases: ['Serenade Manhwa', 'Keum Kavi'],
    kitsuType: 'manga',
    searchQuery: 'Serenade Keum Kavi'
  },
  {
    id: 'ghosts-of-greywoods',
    title: 'Ghosts of Greywoods',
    romaji: 'Ghosts of Greywoods',
    nativeTitle: '그레이우드의 유령들',
    medium: 'Manhwa',
    releaseYear: 2020,
    origin: 'South Korea',
    setting: 'Historical/Period',
    tropes: ['Master & Servant', 'Opposites Attract'],
    tone: 'Dark/Psychological',
    status: 'Completed',
    synopsis: 'In 19th-century Victorian England, impoverished maid Tamara arrives at the ominous Greywoods Manor to care for Collin, a sickly young lady confined to her bed. Dark family curses and hidden passions intertwine.',
    famousQuote: 'The ghosts of this estate cannot extinguish the warmth of your hand.',
    pairing: 'Tamara x Collin',
    aliases: ['Ghosts of Greywoods', 'Greywoods', 'Dopamine'],
    kitsuType: 'manga',
    searchQuery: 'Ghosts of Greywoods'
  },
  {
    id: 'sadistic-beauty-side-b',
    title: 'Sadistic Beauty: Side Story B',
    romaji: 'Sadistic Beauty: Side Story B',
    nativeTitle: '새디스틱 뷰티: 외전 B',
    medium: 'Manhwa',
    releaseYear: 2020,
    origin: 'South Korea',
    setting: 'College/University',
    tropes: ['Enemies to Lovers', 'Opposites Attract'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'The acclaimed yuri side-story spinoff of Sadistic Beauty: Cold, guarded Gyerin and innocent, warm Minju navigate intense psychological boundaries, vulnerability, and erotic devotion.',
    famousQuote: 'I never let anyone inside my walls... why did you have to break through?',
    pairing: 'Gyerin x Minju',
    aliases: ['Sadistic Beauty Side B', 'Gyerin Minju', 'Woo Yeon-hee'],
    kitsuType: 'manga',
    searchQuery: 'Sadistic Beauty'
  },
  {
    id: 'show-me-your-bust',
    title: 'Show Me Your Bust',
    romaji: 'Show Me Your Bust',
    nativeTitle: '가슴 좀 만져봐도 될까요?',
    medium: 'Manhwa',
    releaseYear: 2019,
    origin: 'South Korea',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Roommates'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'A hilarious high school romantic comedy following Suyeon, who gets caught in embarrassing misunderstandings with glamorous beauty Jiyoung, leading to outrageous situations and undeniable mutual affection.',
    famousQuote: 'One misunderstanding after another, and now I can\'t imagine life without you!',
    pairing: 'Suyeon x Jiyoung',
    aliases: ['Show Me Your Bust', 'Jiyoung Suyeon'],
    kitsuType: 'manga',
    searchQuery: 'Show Me Your Bust'
  },
  {
    id: 'green-tea-bitch',
    title: 'Green Tea Bitch',
    romaji: 'Lvcha Nvpei Dengchang',
    nativeTitle: '绿茶女配登场',
    medium: 'Manhua',
    releaseYear: 2021,
    origin: 'China',
    setting: 'Workplace',
    tropes: ['Enemies to Lovers', 'Opposites Attract'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'Su Tang transmigrates into a romance novel as the scheming "green tea bitch" antagonist tasked with seducing the male lead. Instead, she falls head-over-heels for the elegant, untouchable female lead Tang Wan.',
    famousQuote: 'Who cares about the male lead? The heroine is ten thousand times prettier!',
    pairing: 'Su Tang x Tang Wan',
    aliases: ['Green Tea Bitch', 'Su Tang', 'Tang Wan'],
    kitsuType: 'manga',
    searchQuery: 'Green Tea Bitch'
  },
  {
    id: 'kimi-ga-shinu-made',
    title: 'I Want to Love You Until You Die',
    romaji: 'Kimi ga Shinu Made Koi wo Shitai',
    nativeTitle: '君が死ぬまで恋をしたい',
    medium: 'Manga',
    releaseYear: 2018,
    origin: 'Japan',
    setting: 'Fantasy/Magic',
    tropes: ['Opposites Attract', 'Roommates'],
    tone: 'Dark/Psychological',
    status: 'Ongoing',
    synopsis: 'In a magic military orphanage training orphaned children into disposable weapons for war, immortal test subject Shiina arrives covered in scars. She meets gentle healer Mimi, who vows to love her until death parts them.',
    famousQuote: 'In this school of death, loving you is the only reason my heart beats.',
    pairing: 'Shiina x Mimi',
    aliases: ['Kimi ga Shinu Made Koi wo Shitai', 'Aono Nachi', 'Shiina Mimi'],
    kitsuType: 'manga',
    searchQuery: 'Kimi ga Shinu made Koi wo Shitai'
  },
  {
    id: 'murcielago',
    title: 'Murcielago',
    romaji: 'Murciélago',
    nativeTitle: 'ムルシエラゴ',
    medium: 'Manga',
    releaseYear: 2013,
    origin: 'Japan',
    setting: 'Workplace',
    tropes: ['Opposites Attract', 'Roommates'],
    tone: 'Action/Adventure',
    status: 'Ongoing',
    synopsis: 'Mass-murderer Kuroko Koumori is offered a deal by the Japanese police: avoid execution by becoming a state executioner hunting monstrous criminal syndicates. In her downtime, Kuroko seduces every gorgeous woman in sight.',
    famousQuote: 'I slaughter monsters by day and charm beauties all night long.',
    pairing: 'Kuroko Koumori x Hinako Sakura',
    aliases: ['Murcielago', 'Yoshimurakana', 'Kuroko Hinako'],
    kitsuType: 'manga',
    searchQuery: 'Murcielago'
  },
  {
    id: 'hana-to-hina',
    title: 'Hana & Hina After School',
    romaji: 'Hana to Hina wa Houkago',
    nativeTitle: 'ハナとヒナは放課後',
    medium: 'Manga',
    releaseYear: 2015,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Roommates'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Milk Morinaga\'s delightful high school romance: Petite, hardworking Hana works part-time at a cute character goods store. When tall, fashionable gyaru Hina is hired at the same shop, a sweet after-school secret romance begins.',
    famousQuote: 'Our part-time shift ends, but our feelings are just clocking in.',
    pairing: 'Hana Hasegawa x Hina Emori',
    aliases: ['Hana & Hina After School', 'Hana to Hina wa Houkago', 'Milk Morinaga'],
    kitsuType: 'manga',
    searchQuery: 'Hana to Hina wa Houkago'
  },
  {
    id: 'kanamemo',
    title: 'Kanamemo',
    romaji: 'Kanamemo',
    nativeTitle: 'かなめも',
    medium: 'Anime',
    releaseYear: 2009,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Roommates', 'Opposites Attract'],
    tone: 'Sweet/Fluff',
    status: 'Completed',
    synopsis: 'Orphaned middle schooler Kana Nakamachi finds a job and lodging at the Fuhshin Gazette newspaper delivery office. Living alongside open lesbian couple Yuhki and Hinata, Kana experiences warm, lively daily companionship.',
    famousQuote: 'Delivering morning papers is hard work, but this home is filled with warmth.',
    pairing: 'Yuhki Hirose x Hinata Azuma',
    aliases: ['Kanamemo', 'Feel', 'Yuhki Hinata'],
    kitsuType: 'anime',
    searchQuery: 'Kanamemo'
  },
  {
    id: 'shoujo-sect',
    title: 'Shoujo Sect',
    romaji: 'Shoujo Sect: Innocent Lovers',
    nativeTitle: '少女セクト',
    medium: 'Anime',
    releaseYear: 2008,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Childhood Friends', 'Opposites Attract', 'Enemies to Lovers'],
    tone: 'Drama/Angst',
    status: 'Completed',
    synopsis: 'Ken Kurogane\'s classic high school drama: Shinobu and Momoko were intimate friends in childhood. Reunited in high school, Shinobu is now a rebel gyaru while Momoko is a prim student council member, reigniting intense passion.',
    famousQuote: 'No matter how much our lives change, you were always my first love.',
    pairing: 'Shinobu Handa x Momoko Naito',
    aliases: ['Shoujo Sect', 'Ken Kurogane', 'Shinobu Momoko', 'Amistad'],
    kitsuType: 'anime',
    searchQuery: 'Shoujo Sect'
  },
  {
    id: 'hen-yuri',
    title: 'HEN (Strange)',
    romaji: 'Hen',
    nativeTitle: '変',
    medium: 'Anime',
    releaseYear: 1997,
    origin: 'Japan',
    setting: 'High School',
    tropes: ['Opposites Attract', 'Enemies to Lovers'],
    tone: 'Comedy',
    status: 'Completed',
    synopsis: 'Gantz creator Hiroya Oku\'s early landmark work: Gorgeous school beauty Chizuru Yoshida is completely infatuated with quirky, tomboyish transfer student Azumi Yamada, pursuing her with shameless romantic determination.',
    famousQuote: 'Everyone worships me, but the only girl I want to look at is you!',
    pairing: 'Chizuru Yoshida x Azumi Yamada',
    aliases: ['Hen', 'Hiroya Oku', 'Chizuru Azumi'],
    kitsuType: 'anime',
    searchQuery: 'Hen'
  }
];

export { newSeriesDefs };
